#!/usr/bin/env node
'use strict';
// Actual production functions. Synthetic bytes and controlled storage/media only.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..')),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const slice=(a,b)=>{const start=html.indexOf(a),end=html.indexOf(b,start);assert(start>=0&&end>start,a);return html.slice(start,end)};
const fn=name=>{const start=html.search(new RegExp('(?:async )?function '+name+'\\('));assert(start>=0,name);const end=html.indexOf('\n}',start);assert(end>start,name);return html.slice(start,end+2)};
const noop=()=>{},deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
const rows=[['seyPlayRec','seyyid','seyStop','sey'],['tovbePlayRec','tovbe','tovbeStop','tv'],['akPlayRec','ak','akStop','ak'],['dhPlayRec','salavat','dhStop','dh'],['fsPlayRec','fatiha','fsStop','fs']];
function fixture(){
 const audios=[];
 const clip=new Blob(['synthetic prayer'],{type:'audio/wav'}),nodes={},logs=[],messages=[],played=[],data=new Map(),revisions=new Map();
 const node=id=>nodes[id]||(nodes[id]={textContent:'',innerHTML:'',hidden:false,title:'',classList:{toggle:noop,remove:noop,add:noop},style:{setProperty:noop},querySelector:()=>null});
 const c={Blob,Date,Math,Promise,Error,Number,String,Set,Object,clearTimeout,setTimeout,document:{getElementById:node,querySelectorAll:()=>[],hidden:false},DUAREC:{defs:{},has:{},blobCache:{}},SEY:{gen:0},TV:{queue:[],qi:0},AK:{queue:[],qi:0},DH:{queue:[],qi:0},FS:{queue:[],qi:0},TVK:{has:{}},DL:{has:{}},SVK:{has:{}},SES:{ler:new Set(),ad:null},RECPLAYING:false,
  REC_DB:{get:async k=>data.get(k),del:async k=>{data.delete(k);revisions.set(k,(revisions.get(k)||0)+1)},revision:k=>revisions.get(k)||0},
  confirm:()=>true,vib:noop,duaOnlySync:noop,ac:noop,LOG:{push:x=>logs.push(x)},toast:x=>messages.push(x),hesc:String,
  skRecordingCatalogWarning:()=> 'Kayıt deposu okunamadı. Bu, kayıtların silindiği anlamına gelmez.',skRecordingDeleteWarning:()=> 'Kayıt silinemedi. Listede korundu.',
  speechSynthesis:{cancel:noop,speak:()=>{throw Error('Unexpected TTS fallback')}},
  okuyucularDurdur:noop,svkGosterge:noop,svkGostergeKapat:noop,svkDugmeTazele:noop,miniDenetimSync:noop,tvkBtnTazele:noop,tvkSeyirNext:noop,
  dlDolu:()=>true,dlCalarGoster:noop,dlSatirVurgula:noop,dlIlerlemeYaz:noop,dlId:i=>i,dlWatchOff:noop,dlWatchOn:noop,dlParcala:()=>[],
  URL:{createObjectURL:()=> 'blob:synthetic',revokeObjectURL:noop},Audio:class{constructor(){audios.push(this)}play(){return Promise.resolve()}pause(){}},kayitZinciriKur:()=>true,KAYIT:{mekan:false},KAYIT_RAF:null,ZVOL:1,tvClearWatch:noop,dhClearWatch:noop,akClearWatch:noop,fsClearWatch:noop,tvHi:noop,dhHi:noop,TOVBE_P:[],SALAVAT_P:[],AYETULKURSI:[],navigator:{},
  TOVBE_KISIM:[{ad:'A',p:[]}],SALAVAT_KISIM:[{ad:'A',p:[0]}],DELAIL_HIZB:[{}],tvkKey:i=>'dua:tovbe:'+i,svkKey:i=>'dua:salavat:'+i,dlKey:i=>'dua:delail:'+i,
  tvkRender:noop,dlRender:noop,dhKisimSync:noop,playRecording:async(b,ad,opt)=>{played.push({b,ad,opt});return true}
 };c.window=c;c.$=s=>node(s.slice(1));c.$$=()=>[];
 for(const [,id] of rows){c.DUAREC.defs[id]={key:'dua:'+id,title:id};c.DUAREC.has[id]=true;c.DUAREC.blobCache[id]=clip;data.set('dua:'+id,clip)}
 vm.createContext(c);vm.runInContext(slice('async function duaRecReadState(','async function duaRecToggle(')+slice('async function duaRecPlay(','/* ════ MERKEZÎ SES OTORİTESİ')+rows.map(([play,,stop])=>fn(play)+'\n'+fn(stop)).join('\n')+'\n'+['tvkInit','dlInit','svkInit','tvkSil','tvkOynat','tvkSeyirStop','tvkSeyirPlay','tvkSeyirKayit','tvkSeyirTTS','tvKisimlariCal','dhKisimlariCal','svkKisimOku','svkKisimDurdur','dlOku','dlStop','dlTamOku','dlSonraki'].map(fn).join('\n'),c);
 return {c,clip,nodes,logs,messages,played,data,revisions,audios};
}
const results=[];async function test(name,run){let timer;try{await Promise.race([run(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Fixture did not settle')),2000)})]);results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:e.stack})}finally{clearTimeout(timer)}}
(async()=>{
 for(const [play,id,stop,prefix] of rows){
  await test(id+': completed clip logs exactly once',async()=>{const h=fixture();assert.equal(await h.c[play](),true);assert.equal(h.logs.length,1);assert.equal(h.played.length,1);assert.equal(h.c.DUAREC.attempt.cancelled,true)});
  await test(id+': false playback cannot report success or log',async()=>{const h=fixture();h.c.playRecording=async()=>false;assert.equal(await h.c[play](),false);assert.equal(h.logs.length,0);assert.doesNotMatch(h.nodes[prefix+'Prog']?.textContent||'',/Tamamlandı/)});
  await test(id+': rejected playback cannot report success or log',async()=>{const h=fixture();h.c.playRecording=async()=>{throw Error('NotAllowedError')};assert.equal(await h.c[play](),false);assert.equal(h.logs.length,0)});
  await test(id+': Stop fences late successful callback and duplicate resolution',async()=>{const h=fixture(),late=deferred();h.c.playRecording=()=>late.promise;const p=h.c[play]();h.c[stop](false);const text=JSON.stringify(h.nodes);late.resolve(true);late.resolve(true);assert.equal(await p,false);assert.equal(h.logs.length,0);assert.equal(JSON.stringify(h.nodes),text)});
  await test(id+': earlier attempt cannot clear newer active reader or log',async()=>{const h=fixture(),old=deferred(),fresh=deferred();let n=0;h.c.playRecording=()=>++n===1?old.promise:fresh.promise;const p=h.c[play](),q=h.c[play]();const text=JSON.stringify(h.nodes);old.resolve(true);assert.equal(await p,false);assert.equal(h.logs.length,0);assert.equal(JSON.stringify(h.nodes),text);fresh.resolve(true);assert.equal(await q,true);assert.equal(h.logs.length,1)});
  await test(id+': stopped pending storage read cannot start late playback',async()=>{const h=fixture(),late=deferred();delete h.c.DUAREC.blobCache[id];h.c.REC_DB.get=()=>late.promise;const p=h.c[play]();h.c[stop](false);const text=JSON.stringify(h.nodes);late.resolve(h.clip);assert.equal(await p,false);assert.equal(h.played.length,0);assert.equal(h.logs.length,0);assert.equal(JSON.stringify(h.nodes),text)});
 }
 for(const [stop,id] of [['seyStop','seyyid'],['akStop','ak'],['fsStop','fatiha']])await test(stop+': explicitly stops only its own physical whole-prayer recording',async()=>{const h=fixture(),stops=[];h.c.sesDurdur=reason=>stops.push(reason);h.c.SES.ad='dua:'+id;h.c[stop](false);assert.deepEqual(stops,['prayer-stop']);h.c.SES.ad='other-reader';h.c[stop](false);assert.equal(stops.length,1)});
 await test('Seyyid Stop and recorded restart invalidate old TTS generation',async()=>{const h=fixture();h.c.SEY.gen=4;h.c.seyStop(false);assert.equal(h.c.SEY.gen,5);await h.c.seyPlayRec();assert.equal(h.c.SEY.gen,6)});
 await test('New prayer fences old different-prayer completion and state writes',async()=>{const h=fixture(),old=deferred(),fresh=deferred();h.c.playRecording=(_b,ad)=>ad==='dua:seyyid'?old.promise:fresh.promise;const p=h.c.seyPlayRec(),q=h.c.akPlayRec();const text=JSON.stringify(h.nodes);old.resolve(true);assert.equal(await p,false);assert.equal(JSON.stringify(h.nodes),text);fresh.resolve(true);assert.equal(await q,true);assert.equal(h.logs.length,1)});
 await test('Voice ownership/preference fence prevents stale completion credit',async()=>{const h=fixture(),late=deferred();let owns=true;h.c.SukunVoiceAttempt={capture:opt=>()=>owns&&opt.isCurrent()};h.c.playRecording=()=>late.promise;const p=h.c.seyPlayRec();owns=false;late.resolve(true);assert.equal(await p,false);assert.equal(h.logs.length,0)});
 await test('Known prayer read failure retains presence, cache and visible menu',async()=>{const h=fixture();h.c.REC_DB.get=async()=>{throw Error('SecurityError')};await h.c.duaRecInit();assert.equal(h.c.DUAREC.has.seyyid,true);assert.equal(h.c.DUAREC.blobCache.seyyid,h.clip);assert.equal(h.c.DUAREC.readError.seyyid,true);assert.equal(h.nodes.duaRecMenu_seyyid.hidden,false);assert.match(h.nodes.duaRec_seyyid.title,/silindiği anlamına gelmez/);assert.equal(await h.c.seyPlayRec(),false);assert.equal(h.played.length,0);assert.equal(h.logs.length,0)});
 await test('Cold failed read is unknown and retry can find the original recording',async()=>{const h=fixture();h.c.DUAREC.has={};h.c.DUAREC.blobCache={};h.c.REC_DB.get=async()=>{throw Error('SecurityError')};await h.c.duaRecInit();assert.equal(h.c.DUAREC.has.seyyid,null);assert.equal(h.c.duaRecAvailable('seyyid'),true);h.c.REC_DB.get=async k=>h.data.get(k);assert.equal(await h.c.seyPlayRec(),true);assert.equal(h.c.DUAREC.readError.seyyid,false);assert.equal(h.logs.length,1)});
 await test('Successful empty retry alone clears presence and old cache',async()=>{const h=fixture();h.c.REC_DB.get=async()=>null;await h.c.duaRecInit();assert.equal(h.c.DUAREC.has.seyyid,false);assert.equal(h.c.DUAREC.blobCache.seyyid,undefined);assert.equal(h.c.DUAREC.readError.seyyid,false)});
 await test('Late failed scan cannot overwrite fresh successful scan',async()=>{const h=fixture(),old=deferred();let n=0;h.c.REC_DB.get=()=>++n===1?old.promise:Promise.resolve(h.clip);const p=h.c.duaRecReadState(h.c.DUAREC,'seyyid','dua:seyyid');assert.equal((await h.c.duaRecReadState(h.c.DUAREC,'seyyid','dua:seyyid')).ok,true);old.reject(Error('late'));assert.equal((await p).stale,true);assert.equal(h.c.DUAREC.readError.seyyid,false)});
 await test('Late missing scan cannot hide a newly committed recording',async()=>{const h=fixture(),old=deferred();h.c.REC_DB.get=()=>old.promise;const p=h.c.duaRecReadState(h.c.DUAREC,'seyyid','dua:seyyid');h.c.duaRecKnown(h.c.DUAREC,'seyyid',h.clip);old.resolve(null);assert.equal((await p).stale,true);assert.equal(h.c.DUAREC.has.seyyid,true)});
 await test('Failed prayer delete preserves cache/menu/original bytes and warns',async()=>{const h=fixture();h.c.REC_DB.del=async()=>{throw Error('SecurityError')};h.c.duaRecSyncUI('seyyid');assert.equal(await h.c.duaRecDelete('seyyid'),false);assert.equal(h.c.DUAREC.has.seyyid,true);assert.equal(h.c.DUAREC.blobCache.seyyid,h.clip);assert.equal(h.nodes.duaRecMenu_seyyid.hidden,false);assert.equal(h.data.get('dua:seyyid'),h.clip);assert.match(h.messages[0],/silinemedi/)});
 await test('Confirmed committed prayer delete alone clears metadata',async()=>{const h=fixture();assert.equal(await h.c.duaRecDelete('seyyid'),true);assert.equal(h.c.DUAREC.has.seyyid,false);assert.equal(h.c.DUAREC.blobCache.seyyid,undefined);assert.equal(h.nodes.duaRecMenu_seyyid.hidden,true);assert.equal(h.data.has('dua:seyyid'),false)});
 await test('Declined prayer delete leaves storage and metadata untouched',async()=>{const h=fixture();h.c.confirm=()=>false;assert.equal(await h.c.duaRecDelete('seyyid'),false);assert.equal(h.data.get('dua:seyyid'),h.clip);assert.equal(h.c.DUAREC.has.seyyid,true);assert.equal(h.messages.length,0)});
 await test('Failed section delete preserves known metadata and warns without success',async()=>{const h=fixture();h.c.TVK.has[0]=true;h.c.REC_DB.del=async()=>{throw Error('SecurityError')};assert.equal(await h.c.tvkSil(0),false);assert.equal(h.c.TVK.has[0],true);assert.match(h.messages[0],/silinemedi/);assert.equal(h.messages.length,1)});
 for(const [name,state] of [['tvkInit','TVK'],['dlInit','DL'],['svkInit','SVK']])await test(name+': read failure retains known presence and marks unavailable',async()=>{const h=fixture();h.c[state].has[0]=true;h.c.REC_DB.get=async()=>{throw Error('SecurityError')};await h.c[name]();assert.equal(h.c[state].has[0],true);assert.equal(h.c[state].readError[0],true)});
 for(const [name,state,key] of [['tvKisimlariCal','TVK','dua:tovbe:0'],['dhKisimlariCal','SVK','dua:salavat:0']]){
  await test(name+': unavailable recording stops before TTS, media or completion log',async()=>{const h=fixture();h.c[state].has[0]=null;h.c[state].readError={0:true};h.c.REC_DB.get=async()=>{throw Error('SecurityError')};assert.equal(await h.c[name](),false);assert.equal(h.played.length,0);assert.equal(h.logs.length,0)});
  await test(name+': failed recorded part cannot credit whole prayer',async()=>{const h=fixture();h.c[state].has[0]=true;h.data.set(key,h.clip);h.c.playRecording=async()=>false;assert.equal(await h.c[name](),false);assert.equal(h.logs.length,0)});
  await test(name+': Stop fences late section read and cannot clear a newer attempt',async()=>{const h=fixture(),late=deferred();h.c[state].has[0]=true;h.c.REC_DB.get=()=>late.promise;const p=h.c[name]();h.c.duaRecCancel();const fresh=h.c.duaRecBegin('seyyid');late.resolve(h.clip);assert.equal(await p,false);assert.equal(h.played.length,0);assert.equal(h.c.DUAREC.attempt,fresh);assert.equal(h.logs.length,0)});
  await test(name+': completed recorded part logs one whole-prayer completion',async()=>{const h=fixture();h.c[state].has[0]=true;h.data.set(key,h.clip);await h.c[name]();assert.equal(h.played.length,1);assert.equal(h.logs.length,1)});
 }
 await test('Section preview read failure is visible and retains known presence',async()=>{const h=fixture();h.c.TVK.has[0]=true;h.c.REC_DB.get=async()=>{throw Error('SecurityError')};assert.equal(await h.c.tvkOynat(0),false);assert.equal(h.c.TVK.has[0],true);assert.match(h.messages[0],/silindiği anlamına gelmez/)});
 await test('Section preview canceled during read cannot start playback',async()=>{const h=fixture(),late=deferred();h.c.REC_DB.get=()=>late.promise;const p=h.c.tvkOynat(0);h.c.duaRecCancel();late.resolve(h.clip);assert.equal(await p,false);assert.equal(h.played.length,0)});
 await test('Serial panel read rejection stops without step credit or TTS',async()=>{const h=fixture();h.c.TVK.attempt=h.c.duaRecBegin('tovbe');h.c.TVK.playing=true;h.c.TVK.i=0;h.c.REC_DB.get=async()=>{throw Error('SecurityError')};await h.c.tvkSeyirKayit(0);assert.equal(h.c.TVK.playing,false);assert.equal(h.c.TVK.i,0);assert.equal(h.audios.length,0)});
 await test('Serial panel media error and duplicate ended event cannot credit a step',async()=>{const h=fixture();h.data.set('dua:tovbe:0',h.clip);h.c.TVK.attempt=h.c.duaRecBegin('tovbe');h.c.TVK.playing=true;h.c.TVK.i=0;await h.c.tvkSeyirKayit(0);const a=h.audios[0],ended=a.onended,error=a.onerror;error();ended();ended();assert.equal(h.c.TVK.i,0);assert.equal(h.c.TVK.playing,false)});
 await test('Serial source canceled by failing preview releases only its owned physical audio',async()=>{const h=fixture();let pauses=0;h.data.set('dua:tovbe:0',h.clip);h.c.tvkSeyirPlay();await h.c.tvkSeyirKayit(0);const old=h.audios[0],ended=old.onended;old.pause=()=>pauses++;assert.equal(h.c.SES.ler.has(old),true);h.c.REC_DB.get=async()=>{throw Error('SecurityError')};assert.equal(await h.c.tvkOynat(0),false);assert.equal(pauses,1);assert.equal(h.c.SES.ler.has(old),false);assert.equal(h.c.TVK.audio,null);assert.equal(h.c.TVK.playing,false);ended();assert.equal(h.c.TVK.i,0)});
 await test('Serial panel real ended event credits its step only once',async()=>{const h=fixture();h.data.set('dua:tovbe:0',h.clip);h.c.TVK.attempt=h.c.duaRecBegin('tovbe');h.c.TVK.playing=true;h.c.TVK.i=0;await h.c.tvkSeyirKayit(0);const ended=h.audios[0].onended;ended();ended();assert.equal(h.c.TVK.i,1)});
 await test('Serial panel Stop rejects late stored clip before audio creation',async()=>{const h=fixture(),late=deferred();h.c.TVK.attempt=h.c.duaRecBegin('tovbe');h.c.TVK.playing=true;h.c.TVK.i=0;h.c.REC_DB.get=()=>late.promise;const p=h.c.tvkSeyirKayit(0);h.c.tvkSeyirStop();late.resolve(h.clip);await p;assert.equal(h.audios.length,0);assert.equal(h.c.TVK.i,0)});
 await test('Serial TTS old/duplicate callbacks cannot credit a restarted attempt',async()=>{const h=fixture(),spoken=[];h.c.$=()=>null;Object.assign(h.c,{TV_ONLY:false,SPK:{rate:1},spkPitch:()=>1,SpeechSynthesisUtterance:class{},TOVBE_KISIM:[{p:[0]},{p:[1]}],TOVBE_P:['old','new']});h.c.speechSynthesis.speak=u=>spoken.push(u);h.c.TVK.attempt=h.c.duaRecBegin('tovbe');h.c.TVK.playing=true;h.c.TVK.i=0;h.c.tvkSeyirTTS(0);const old=spoken[0];h.c.duaRecCancel();h.c.TVK.attempt=h.c.duaRecBegin('tovbe');h.c.TVK.playing=true;h.c.TVK.i=0;h.c.tvkSeyirTTS(0);old.onend();old.onend();assert.equal(h.c.TVK.i,0);spoken[1].onend();spoken[1].onend();assert.equal(h.c.TVK.i,1)});
 await test('Delail old TTS callback settles only its own promise and preserves new reader',async()=>{const h=fixture(),spoken=[];Object.assign(h.c,{SPK:{rate:1},spkPitch:()=>1,SpeechSynthesisUtterance:class{},dlParcala:()=>[{t:'synthetic',ar:false}]});h.c.speechSynthesis.speak=u=>spoken.push(u);const old=h.c.dlOku(0),oldUtterance=spoken[0],fresh=h.c.dlOku(1),owner=h.c.DL._cozul;oldUtterance.onend();oldUtterance.onend();await old;assert.equal(h.c.DL._cozul,owner);assert.equal(h.c.DL.playing,true);assert.equal(h.c.DL.hedefHizb,1);spoken[1].onend();spoken[1].onend();await fresh;assert.equal(h.c.DL.playing,false);assert.equal(h.c.DL._cozul,null)});
 await test('Text section unavailable source stops chain without selecting TTS',async()=>{const h=fixture();h.c.SVK.has[0]=null;h.c.SVK.readError={0:true};h.c.REC_DB.get=async()=>{throw Error('SecurityError')};await h.c.svkKisimOku(0,[{p:[]}],()=> 'dua:salavat:0',h.c.SVK.has,'#dhText',false);assert.equal(h.c.SVK.zincir,false);assert.equal(h.c.SVK.okunan,null);assert.equal(h.played.length,0);assert.match(h.messages[0],/silindiği anlamına gelmez/)});
 await test('Canceled text section read cannot start late media',async()=>{const h=fixture(),late=deferred();h.c.SVK.has[0]=true;h.c.REC_DB.get=()=>late.promise;const p=h.c.svkKisimOku(0,[{p:[]}],()=> 'dua:salavat:0',h.c.SVK.has,'#dhText',false);h.c.svkKisimDurdur();late.resolve(h.clip);await p;assert.equal(h.played.length,0);assert.equal(h.c.SVK.okunan,null)});
 await test('Older same-section completion cannot clear replacement section',async()=>{const h=fixture(),late=deferred(),fresh=deferred();h.c.SVK.has[0]=true;h.data.set('dua:salavat:0',h.clip);let n=0;h.c.playRecording=()=>++n===1?late.promise:fresh.promise;const p=h.c.svkKisimOku(0,[{p:[]}],()=> 'dua:salavat:0',h.c.SVK.has,'#dhText',false);await Promise.resolve();await Promise.resolve();h.c.svkKisimDurdur();const q=h.c.svkKisimOku(0,[{p:[]}],()=> 'dua:salavat:0',h.c.SVK.has,'#dhText',false);await Promise.resolve();await Promise.resolve();const owner=h.c.SVK.okunan;late.resolve(true);await p;assert.equal(h.c.SVK.okunan,owner);fresh.resolve(true);await q;assert.equal(h.c.SVK.okunan,null)});
 await test('Delail read error stops chain and retains known clip presence',async()=>{const h=fixture();h.c.DL.has[0]=true;h.c.DL.zincir=true;h.c.REC_DB.get=async()=>{throw Error('SecurityError')};assert.equal(await h.c.dlOku(0),false);assert.equal(h.c.DL.zincir,false);assert.equal(h.c.DL.has[0],true);assert.equal(h.played.length,0)});
 await test('Delail failed recorded hizb stops chain before next hizb',async()=>{const h=fixture();h.c.dlSiraYap=()=>[0,1];h.c.DL.has={0:true,1:true};h.data.set('dua:delail:0',h.clip);h.data.set('dua:delail:1',h.clip);const calls=[];h.c.playRecording=async(_b,ad)=>{calls.push(ad);return false};await h.c.dlTamOku('all');assert.deepEqual(calls,['delail:0']);assert.equal(h.c.DL.zincir,false);assert.equal(h.c.DL.kayitCaliyor,false);assert.match(h.messages[0],/tamamlanmadı/)});
 await test('Delail explicit Next still advances a chain without treating skip as failure',async()=>{const h=fixture(),first=deferred();h.c.dlSiraYap=()=>[0,1];h.c.DL.has={0:true,1:true};h.data.set('dua:delail:0',h.clip);h.data.set('dua:delail:1',h.clip);const calls=[];h.c.playRecording=async(_b,ad)=>{calls.push(ad);return ad==='delail:0'?first.promise:true};h.c.sesDurdur=()=>first.resolve(false);const p=h.c.dlTamOku('all');await new Promise(resolve=>setImmediate(resolve));assert.equal(h.c.DL.kayitCaliyor,true);h.c.dlSonraki();await p;assert.deepEqual(calls,['delail:0','delail:1']);assert.equal(h.messages.length,0)});
 await test('Delayed Delail Next cannot restart after Stop or a newer read attempt',async()=>{for(const action of ['stop','newer','continue']){const h=fixture(),jobs=[],starts=[];h.c.setTimeout=(fn,ms)=>{jobs.push({fn,ms});return jobs.length};h.c.DELAIL_HIZB=[{},{}];Object.assign(h.c.DL,{kayitCaliyor:true,hedefHizb:0,zincir:false,readAttempt:10});h.c.dlOku=i=>starts.push(i);h.c.dlSonraki();if(action==='stop')h.c.dlStop();if(action==='newer')h.c.DL.readAttempt++;for(const job of jobs.filter(x=>x.ms===90))job.fn();assert.deepEqual(starts,action==='continue'?[1]:[])}});
 await test('Cold unavailable Tovbe entry selects recording retry rather than TTS',async()=>{const h=fixture();let recorded=0,tts=0;Object.assign(h.c,{ZIKIR_BIRLIKTE:false,okuyucuAcKapa:()=>false,SPK:{list:['synthetic']},tvNext:()=>tts++,tovbeQueue:()=>{h.c.TV.queue=[0]},tvKisimKaydiVarMi:()=>false,tovbePlayRec:()=>recorded++});h.c.DUAREC.has.tovbe=null;h.c.DUAREC.readError={tovbe:true};vm.runInContext(fn('tovbePlay'),h.c);h.c.tovbePlay();assert.equal(recorded,1);assert.equal(tts,0)});
 await test('Externally invalidated same prayer retires only its own flags',async()=>{const h=fixture(),late=deferred();let valid=true;h.c.SukunVoiceAttempt={capture:opt=>()=>valid&&opt.isCurrent()};h.c.playRecording=()=>late.promise;const p=h.c.seyPlayRec();valid=false;late.resolve(false);await p;assert.equal(h.c.SEY.playing,false);assert.equal(h.c.__seyPlaying,false);assert.equal(h.nodes.seyProg.textContent,'');assert.equal(h.logs.length,0)});
 for(const succeeds of [false,true])await test('Niyet deletion '+(succeeds?'updates metadata only after commit':'failure preserves known clip metadata'),async()=>{const h=fixture();let synced=0;Object.assign(h.c,{NIYET_REC_KEY:'niyet:core',NIYET_HAS_REC:true,NIYET_BLOB:h.clip,niyetRecSyncUI:()=>synced++});h.data.set('niyet:core',h.clip);if(!succeeds)h.c.REC_DB.del=async()=>{throw Error('SecurityError')};vm.runInContext(slice("$('#niyetRecDel').onclick=async()=>{","REC_DB.get(NIYET_REC_KEY).then"),h.c);assert.equal(await h.nodes.niyetRecDel.onclick(),succeeds);assert.equal(h.c.NIYET_HAS_REC,!succeeds);assert.equal(h.c.NIYET_BLOB,succeeds?null:h.clip);assert.equal(synced,succeeds?1:0);assert.equal(h.data.has('niyet:core'),!succeeds);if(!succeeds)assert.match(h.messages[0],/silinemedi/)});
 await test('Delail Stop fences late read before media start',async()=>{const h=fixture(),late=deferred();h.c.DL.has[0]=true;h.c.REC_DB.get=()=>late.promise;const p=h.c.dlOku(0);h.c.dlStop();late.resolve(h.clip);assert.equal(await p,false);assert.equal(h.played.length,0)});
 await test('Global recording Stop cancels pending prayer and resets its owned flags',async()=>{const h=fixture(),late=deferred();vm.runInContext(slice('function sesDurdur(', '/* Bütün metin okuyucularını'),h.c);delete h.c.DUAREC.blobCache.seyyid;h.c.REC_DB.get=()=>late.promise;const p=h.c.seyPlayRec();h.c.sesDurdur('stopped');assert.equal(h.c.__seyPlaying,false);assert.equal(h.c.SEY.playing,false);late.resolve(h.clip);assert.equal(await p,false);assert.equal(h.played.length,0)});
 await test('Soft media handoff does not cancel its preparing prayer attempt',async()=>{const h=fixture();vm.runInContext(slice('function sesDurdur(', '/* Bütün metin okuyucularını'),h.c);const attempt=h.c.duaRecBegin('seyyid');h.c.sesDurdur('superseded');assert.equal(attempt.current(),true)});
 await test('Journey owner claim primes synchronously before async acquisition',async()=>{process.env.SUKUN_AUDIO_SOURCE=root;const {origin}=require(path.join(root,'tests/helpers/tab-owner-origin.cjs'));const world=origin({allowLocks:false}),tab=world.tab();let started=false;const p=tab.owner.run('journey99',()=>{started=true;return true});assert.equal(tab.calls.prime,1);assert.equal(started,false);world.unpauseLocks();await world.flush();assert.equal(await p,true);assert.equal(started,true)});
 await test('Owner prime and frequency Start call ac without startup overlay',async()=>{const binding=html.slice(html.indexOf('window.SukunTabOwner?.bind?.('),html.indexOf('window.SukunTabOwner?.bind?.(')+1800);assert.match(html,/prime:\(\)=>\{try\{ac\(\);if\(ctx\?\.state==='suspended'\)ctx.resume\(\)/);const source=fn('frStart');assert(source.indexOf('ac();')<source.indexOf('makeEnv()'));assert.doesNotMatch(source,/acilisPerde/)});
 await test('ERROR keeps manual gate closed but explains Retry and Finish',async()=>{const c={Object,Number,Math,String,document:{hidden:false},SukunSessionState:{snapshot:()=>({phase:'ERROR'})}};c.window=c;vm.createContext(c);vm.runInContext(slice('window.SukunCountCorrection=(()=>{','\n\n\nfunction rep(){'),c);const gate=c.SukunCountCorrection.status(1);assert.equal(gate.allowed,false);assert.match(gate.reason,/Yeniden dene/);assert.match(gate.reason,/Bitir/);assert.doesNotMatch(gate.reason,/önce duraklat/)});
 await test('ERROR primary visual and accessible labels both expose retry',async()=>{const ui=fs.readFileSync(path.join(root,'assets/runtime/interface-r920.js'),'utf8'),start=ui.indexOf(" const busy=s.phase==='PLAYING'"),end=ui.indexOf(' for(const [id,label]',start),labels={};const c={s:{phase:'ERROR'},$:x=>x,text:(id,value)=>labels[id]=value};vm.createContext(c);vm.runInContext(ui.slice(start,end)+';globalThis.actions=actionNames;',c);assert.equal(labels.r927PlayCaption,'Yeniden dene');assert.equal(c.actions.r920Play,'Sesi yeniden dene')});
 const storageSource=fs.readFileSync(path.join(root,'tests/recording-storage.cjs'),'utf8').split('const results=[]')[0],{fixture:storage,bounded}=new Function('require','__dirname','process',storageSource+';return {fixture,bounded};')(require,path.join(root,'tests'),{argv:['node','fixture',path.join(root,'index.html')]});
 await test('Delete abort rejects promptly and preserves original stored bytes',async()=>{const f=storage();await f.test.db.set('esma:7:tev',f.blob);f.faults.abort=true;const r=await bounded(f.test.db.del('esma:7:tev'));assert.equal(r.error,'AbortError');assert.equal(f.disk.get('esma:7:tev'),f.blob);assert.equal(f.opens(),1)});
 await test('Delete timeout aborts without replay or loss of last-known catalog',async()=>{const f=storage();await f.test.db.set('esma:7:tev',f.blob);f.faults.scanLag=60;const r=await bounded(f.test.db.del('esma:7:tev',{timeoutMs:5}));assert.equal(r.error,'RecordingDeleteTimeout');assert.equal(f.disk.get('esma:7:tev'),f.blob);assert.deepEqual([...f.test.keys()],['esma:7:tev']);assert.equal(f.opens(),1)});
 await test('Late/duplicate delete completion after timeout cannot invalidate metadata',async()=>{const f=storage();await f.test.db.set('esma:7:tev',f.blob);let tx;const conn=f.connections[0],original=conn.transaction;conn.transaction=function(...args){tx=original.apply(this,args);return tx};f.faults.scanLag=60;const p=bounded(f.test.db.del('esma:7:tev',{timeoutMs:20}));await new Promise(resolve=>setImmediate(resolve));const late=tx.oncomplete;assert.equal((await p).error,'RecordingDeleteTimeout');late();late();assert.equal(f.disk.get('esma:7:tev'),f.blob);assert.deepEqual([...f.test.keys()],['esma:7:tev'])});
 await test('Delete transaction creation failure is not replayed',async()=>{const f=storage();await f.test.db.set('esma:7:tev',f.blob);f.faults.transaction='InvalidStateError';assert.equal((await bounded(f.test.db.del('esma:7:tev'))).error,'InvalidStateError');assert.equal(f.opens(),1);assert.equal(f.disk.get('esma:7:tev'),f.blob)});
 await test('Successful delete settles once after commit and removes catalog key',async()=>{const f=storage();await f.test.db.set('esma:7:tev',f.blob);assert.equal(await f.test.db.del('esma:7:tev'),true);assert.equal(f.disk.size,0);assert.equal(f.test.keys().length,0)});
 const report={root,method:'Actual production functions and synthetic controlled media/IndexedDB/DOM events; no physical browser, audio, microphone, user recording, or OS persistence test.',passed:results.filter(x=>x.passed).length,total:results.length,results};console.log(JSON.stringify(report,null,2));process.exitCode=report.passed===report.total?0:1;
})();
