#!/usr/bin/env node
'use strict';
// Actual source bodies with synthetic clips and controlled DOM/storage endpoints.
// No browser, phone, user recording, reset, or import is involved.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..'));
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const setSource=fs.readFileSync(path.join(root,'assets/runtime/tekke-set-r990.js'),'utf8');
const uxSource=fs.readFileSync(path.join(root,'assets/runtime/tekke-ux-r992.js'),'utf8');
const slice=(a,b)=>{const start=html.indexOf(a),end=html.indexOf(b,start);assert(start>=0&&end>start,a);return html.slice(start,end)};
const production=slice('const SK_RECORDING_CATALOG=','/* r147: Kayıtlarım bağlayıcısı */')+slice('const VERI={','/* ════ OKUMA HIZI')+slice('let veriDurumGeneration=','async function recMgrRender(){')+slice('const IMGREC={','async function imgRecAl(')+slice('let imgBadgeGeneration=','/* ── Suflör:');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
const noop=()=>{};
function node(){return {innerHTML:'',textContent:'',value:'',dataset:{},style:{setProperty:noop},classList:{toggle:noop,add:noop,remove:noop},setAttribute:noop,addEventListener:noop};}
function fixture(initial=['tekke:imge:one:0']){
 const data=new Map(initial.map(key=>[key,new Blob(['synthetic'],{type:'audio/webm'})])),nodes={},badges={},revisions=new Map();
 for(const id of ['veriDurum','imgRecSet','imgRecList','imgRecStat'])nodes[id]=node();nodes.imgRecSet.value='one';
 for(const key of ['one','two'])badges[key]=node();
 let fail=false,reads=0,getHook=null,listHook=null,keyHook=null;
 const c={Blob,Promise,Map,Set,Math,Number,String,Error,Object,Array,Date,JSON,setTimeout,clearTimeout,
  addEventListener:noop,dispatchEvent:noop,CustomEvent:class{constructor(type,options){this.type=type;this.detail=options?.detail;}},
  RECKEYS:new Set(initial),I18N:{lang:'tr',walk:noop},navigator:{storage:{estimate:async()=>({quota:1000,usage:20}),persisted:async()=>true}},S:{get:(k,d)=>d},
  document:{getElementById:id=>nodes[id]||null,querySelector:selector=>{const k=selector.match(/data-kayitli="([^"]+)"/);return k?badges[k[1]]:null;}},$:s=>nodes[s.slice(1)]||null,hesc:String,boyutYaz:n=>'size:'+n,imgMetin:s=>s,
  IMGELEME:{one:{adimlar:[{t:'first'},{t:'second'}]},two:{adimlar:[{t:'other'}]}},SukunTekkeSet:{refresh:noop},
  REC_DB:{revision:k=>revisions.get(k)||0,get:async k=>{reads++;if(getHook)return getHook(k);if(fail)throw Error('SecurityError');return data.get(k)||null;},keys:async()=>{if(keyHook)return keyHook();if(fail)throw Error('SecurityError');return [...data.keys()];},hepsi:async()=>{if(listHook)return listHook();if(fail)throw Error('SecurityError');return [...data].map(([key,b])=>({key,boyut:b.size}));}}
 };c.window=c;vm.createContext(c);vm.runInContext(production+';globalThis.stats=()=>VERI.durum();globalThis.imgState=()=>IMGREC;',c);
 return {c,data,nodes,badges,revisions,fail(v=true){fail=v},get(fn){getHook=fn},list(fn){listHook=fn},keys(fn){keyHook=fn},reads:()=>reads};
}
function setFixture(){
 const data=new Map([['one:0',new Blob(['synthetic original'],{type:'audio/webm'})]]),nodes={},persisted=[],spoken=[];let fail=false,loadHook=null,audios=0;
 const nav={after(el){nodes[el.id]=el}};
 function element(tag){const n=node(),children={};n.querySelector=s=>children[s]||(children[s]=node());n.querySelectorAll=()=>[];n.hidden=false;n.contains=()=>true;
  if(tag==='audio'){audios++;n.pause=noop;n.removeAttribute=noop;n.load=noop;n.play=async()=>{queueMicrotask(()=>{n.onplaying?.();n.onended?.();});};}return n;}
 const c={Blob,Promise,Set,Map,Math,Date,Number,String,Object,Array,JSON,Error,setTimeout,clearTimeout,setInterval,clearInterval,performance:{now:()=>0},URL:{createObjectURL:()=> 'blob:synthetic',revokeObjectURL:noop},
  localStorage:{getItem:()=>null},I18N:{lang:'tr'},addEventListener:noop,
  document:{documentElement:{lang:'tr'},getElementById:id=>nodes[id]||null,querySelector:s=>s==='.wrap > nav.tabs'?nav:null,createElement:element},
  SpeechSynthesisUtterance:function(text){this.text=text},speechSynthesis:{resume:noop,cancel:noop,speak(u){spoken.push(u.text);queueMicrotask(()=>{u.onstart?.();u.onend?.();})}},
 };c.window=c;vm.createContext(c);vm.runInContext(setSource,c);
 const catalog={one:{ad:'One',adimlar:[{t:'first',sn:0},{t:'second',sn:0}]},two:{ad:'Two',adimlar:[{t:'other',sn:0}]}};
 const adapter={load:async(k,i)=>{if(loadHook)return loadHook(k,i);if(fail)throw Error('SecurityError');return data.get(k+':'+i)||null;},persist:(k,v)=>persisted.push({k,v})};
 c.SukunTekkeSet.bind(catalog,adapter);
 return {c,api:c.SukunTekkeSet,data,nodes,persisted,spoken,audios:()=>audios,fail(v=true){fail=v},load(fn){loadHook=fn}};
}
const results=[];async function test(name,fn){try{await fn();results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:e.stack})}}
(async()=>{
 await test('VERI rejected read returns unavailable and null statistics, never zero',async()=>{const h=fixture();h.fail();const d=await h.c.stats();assert.equal(d.ok,false);assert.equal(d.adet,null);assert.equal(d.toplam,null);assert.equal(d.tur,null);assert.equal(d.kota,1000);});
 await test('VERI successful empty read alone returns verified zero',async()=>{const h=fixture([]),d=await h.c.stats();assert.equal(d.ok,true);assert.equal(d.adet,0);assert.equal(d.toplam,0)});
 await test('VERI successful read returns exact size and category counts',async()=>{const h=fixture(),d=await h.c.stats();assert.equal(d.ok,true);assert.equal(d.adet,1);assert.equal(d.toplam,9);assert.equal(d.tur.tefekkür,1)});
 await test('Storage panel renders unavailable warning without zero count or size',async()=>{const h=fixture();h.fail();await h.c.veriDurumYaz();assert.match(h.nodes.veriDurum.innerHTML,/silindiği anlamına gelmez/);assert.match(h.nodes.veriDurum.innerHTML,/Kayıt sayısı<\/span><b>Okunamadı/);assert.doesNotMatch(h.nodes.veriDurum.innerHTML,/Kayıt sayısı<\/span><b>0|size:null/)});
 await test('Storage panel successful retry clears warning and restores exact count',async()=>{const h=fixture();h.fail();await h.c.veriDurumYaz();h.fail(false);await h.c.veriDurumYaz();assert.doesNotMatch(h.nodes.veriDurum.innerHTML,/silindiği anlamına/);assert.match(h.nodes.veriDurum.innerHTML,/Kayıt sayısı<\/span><b>1/)});
 await test('Late failed storage-panel read cannot replace a newer successful render',async()=>{const h=fixture(),old=deferred();let n=0;h.list(()=>++n===1?old.promise:Promise.resolve([{key:'x',boyut:4}]));const p=h.c.veriDurumYaz();await h.c.veriDurumYaz();old.reject(Error('late'));await p;assert.doesNotMatch(h.nodes.veriDurum.innerHTML,/silindiği anlamına/);assert.match(h.nodes.veriDurum.innerHTML,/Kayıt sayısı<\/span><b>1/)});
 await test('Older failed catalog scan is stale and cannot report newer good catalog unavailable',async()=>{const h=fixture(),old=deferred();let n=0;h.keys(()=>++n===1?old.promise:Promise.resolve(['fresh']));const p=h.c.skRecordingCatalogRead();await h.c.skRecordingCatalogRead();old.reject(Error('old failure'));const r=await p;assert.equal(r.stale,true);assert.equal(r.ok,true);assert.deepEqual([...r.keys],['fresh'])});
 await test('Tekke read rejection keeps cached own-recording row and warns instead of absence',async()=>{const h=fixture();await h.c.imgRecTara('one');h.fail();const r=await h.c.imgRecTara('one');assert.equal(r.ok,false);assert.equal(h.c.imgState().has[0],true);assert.match(h.nodes.imgRecList.innerHTML,/data-oynat="0"/);assert.match(h.nodes.imgRecStat.textContent,/silindiği anlamına gelmez/);assert.doesNotMatch(h.nodes.imgRecStat.textContent,/Henüz kayıt yok|cihaz sesi okuyacak/)});
 await test('Tekke cold read rejection is unknown and stops repeated failing reads',async()=>{const h=fixture([]);h.fail();await h.c.imgRecTara('one');assert.equal(h.c.imgState().has[0],null);assert.equal(h.c.imgState().has[1],null);assert.equal(h.reads(),1);assert.doesNotMatch(h.nodes.imgRecStat.textContent,/Henüz kayıt yok/)});
 await test('Tekke unavailable scan cannot copy prior set recording onto a different set',async()=>{const h=fixture();await h.c.imgRecTara('one');h.nodes.imgRecSet.value='two';h.fail();await h.c.imgRecTara('two');assert.equal(h.c.imgState().hasSet,'two');assert.equal(h.c.imgState().has[0],null);assert.doesNotMatch(h.nodes.imgRecList.innerHTML,/data-oynat="0"/)});
 await test('Tekke successful empty scan clears warning and verifies absence',async()=>{const h=fixture([]);h.fail();await h.c.imgRecTara('one');h.fail(false);await h.c.imgRecTara('one');assert.equal(h.c.imgState().readError,'');assert.equal(h.c.imgState().has[0],false);assert.match(h.nodes.imgRecStat.textContent,/Henüz kayıt yok/)});
 await test('Tekke late old-set scan cannot replace newer selected set state',async()=>{const h=fixture(),old=deferred();h.get(k=>k==='tekke:imge:one:0'?old.promise:Promise.resolve(null));const p=h.c.imgRecTara('one');h.nodes.imgRecSet.value='two';await h.c.imgRecTara('two');old.reject(Error('old'));await p;assert.equal(h.c.imgState().hasSet,'two');assert.equal(h.c.imgState().readError,'')});
 await test('Tekke scan cannot hide a newly committed recording behind a late missing read',async()=>{const h=fixture([]),wait=deferred();h.get(k=>k.endsWith(':0')?wait.promise:Promise.resolve(null));const p=h.c.imgRecTara('one');h.c.RECKEYS.add('tekke:imge:one:0');h.revisions.set('tekke:imge:one:0',1);wait.resolve(null);await p;assert.equal(h.c.imgState().has[0],true)});
 await test('Tekke failed badge scan represents all unread sets as unknown',async()=>{const h=fixture();h.fail();await h.c.imgKayitRozetleri();assert.equal(h.badges.one.textContent,'Kayıt deposu okunamadı');assert.equal(h.badges.two.textContent,'Kayıt deposu okunamadı');assert.equal(h.reads(),1)});
 await test('Tekke successful badge retry restores known counts and confirmed emptiness',async()=>{const h=fixture();h.fail();await h.c.imgKayitRozetleri();h.fail(false);await h.c.imgKayitRozetleri();assert.equal(h.badges.one.textContent,'🎙 1 adım kendi sesinle');assert.equal(h.badges.two.textContent,'')});
 await test('Tekke unavailable text is translated in English',async()=>{const h=fixture([]);h.c.I18N.lang='en';h.fail();await h.c.imgRecTara('one');await h.c.imgKayitRozetleri();assert.match(h.nodes.imgRecStat.textContent,/does not mean your recordings were deleted/);assert.equal(h.badges.one.textContent,'Recording storage unreadable')});
 await test('Set readiness failed refresh preserves known count with explicit unavailable state',async()=>{const h=setFixture();await h.api.refresh();assert.equal(h.api.snapshot().recorded,1);h.fail();await h.api.refresh();assert.equal(h.api.snapshot().recorded,1);assert.equal(h.api.snapshot().recordingsAvailable,false);assert.match(h.nodes.r990HomeSetCard.querySelector('.r990SetStatus').textContent,/silindiği anlamına gelmez/)});
 await test('Set cold failed refresh never reports zero or waiting indefinitely',async()=>{const h=setFixture();h.fail();h.api.select('two');await h.api.refresh();assert.equal(h.api.snapshot().recorded,null);assert.equal(h.api.snapshot().recordingsAvailable,false);assert.match(h.nodes.r990HomeSetCard.querySelector('.r990SetStatus').textContent,/silindiği anlamına gelmez/)});
 await test('Set successful empty refresh restores verified zero',async()=>{const h=setFixture();h.fail();await h.api.refresh();h.data.clear();h.fail(false);await h.api.refresh();assert.equal(h.api.snapshot().recorded,0);assert.equal(h.api.snapshot().recordingsAvailable,true)});
 await test('Late failed set readiness refresh cannot clobber newer successful readiness',async()=>{const h=setFixture();await h.api.refresh();const old=deferred();let n=0;h.load(()=>++n===1?old.promise:Promise.resolve(null));const p=h.api.refresh();await h.api.refresh();old.reject(Error('old'));await p;assert.equal(h.api.snapshot().recordingsAvailable,true);assert.equal(h.api.snapshot().recorded,0)});
 await test('Failed set load stops before TTS, audio, credit, or recording-byte changes',async()=>{const h=setFixture();await h.api.refresh();const original=h.data.get('one:0');h.fail();assert.equal(await h.api.start('one'),false);assert.equal(h.api.snapshot().phase,'error');assert.equal(h.api.snapshot().reason,'recording-unavailable');assert.equal(h.api.snapshot().completed,0);assert.equal(h.api.snapshot().recordingsAvailable,false);assert.equal(h.spoken.length,0);assert.equal(h.audios(),0);assert.equal(h.data.get('one:0'),original);assert.equal(h.data.size,1)});
 await test('Confirmed successful missing recording still uses TTS and confirmed completion',async()=>{const h=setFixture();await h.api.refresh();h.data.clear();assert.equal(await h.api.start('one'),true);assert.deepEqual(h.spoken,['first','second']);assert.equal(h.api.snapshot().phase,'ended');assert.equal(h.api.snapshot().completed,2)});
 await test('Successful own recording retains playback priority and stored bytes',async()=>{const h=setFixture();await h.api.refresh();const original=h.data.get('one:0');assert.equal(await h.api.start('one'),true);assert.equal(h.audios(),1);assert.deepEqual(h.spoken,['second']);assert.equal(h.data.get('one:0'),original)});
 await test('Canceled set load remains silent after late storage rejection',async()=>{const h=setFixture();await h.api.refresh();const pending=deferred();h.load(()=>pending.promise);const work=h.api.start('one');await Promise.resolve();h.api.stop();pending.reject(Error('late denial'));assert.equal(await work,false);await Promise.resolve();assert.equal(h.api.snapshot().phase,'idle');assert.equal(h.spoken.length,0);assert.equal(h.audios(),0);assert.equal(h.api.snapshot().completed,0)});
 await test('Tekke entry summary distinguishes unavailable from zero-own-recording TTS',async()=>{const src=uxSource.match(/  const summary=\$\('#r992RecordingSummary'\);[^\n]+/)[0],summary=node();const c={v:{recordingsAvailable:false,recorded:0,selection:{total:2}},$:()=>summary,copy:(tr,en)=>en};vm.createContext(c);vm.runInContext('{'+src+'}',c);assert.match(summary.textContent,/does not mean your recordings were deleted/);assert.doesNotMatch(summary.textContent,/0 your recordings|device voices/);c.v.recordingsAvailable=true;vm.runInContext('{'+src+'}',c);assert.match(summary.textContent,/0 your recordings.*2 device voices/)});
 await test('Read-only presentation scans never change synthetic stored clips',async()=>{const h=fixture(),original=h.data.get('tekke:imge:one:0');await h.c.stats();await h.c.imgRecTara('one');await h.c.imgKayitRozetleri();h.fail();await h.c.stats();await h.c.imgRecTara('one');await h.c.imgKayitRozetleri();assert.equal(h.data.size,1);assert.equal(h.data.get('tekke:imge:one:0'),original);assert.equal(await original.text(),'synthetic')});
 const report={root,method:'Actual shipped catalog, status, Tekke scan, readiness, playback, and entry-summary source with synthetic recording bytes and controlled storage/DOM/media leaves. No physical phone or browser observation.',sourceSha256:crypto.createHash('sha256').update(html).digest('hex'),passed:results.filter(r=>r.passed).length,total:results.length,results};fs.writeFileSync(path.join(__dirname,'recording_unavailable_results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exitCode=report.passed===report.total?0:1;
})().catch(e=>{console.error(e);process.exitCode=1});
