'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..')),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),runtime=fs.readFileSync(path.join(root,'assets/runtime/tekke-sequence-r988.js'),'utf8');
const artworkPath='assets/branding/sukun-selected-logo-r1028.png',asset=fs.readFileSync(path.join(root,artworkPath));
const results=[];function test(name,fn){try{fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
const context={window:{},document:{baseURI:'https://example.test/sukun/nero.html?v=r1028'},URL,Object};vm.createContext(context);const initializer=html.match(/<script id="sukun-media-artwork-r1028">([\s\S]*?)<\/script>/)[1];vm.runInContext(initializer,context);
const expected=JSON.parse(JSON.stringify(context.window.SukunMediaArtworkR1028));
test('Artwork keeps the exact selected clean icon bytes',()=>{assert.deepEqual(asset,fs.readFileSync(path.join(root,'icon-512.png')));assert.equal(crypto.createHash('sha256').update(asset).digest('hex'),'47fb4abe0f7ecf691cb8a68d9b13ff5d46f2cefd507374d63c9d86f9d1c2c7b3');});
test('Artwork declares the real PNG dimensions and format',()=>{assert.equal(asset.readUInt32BE(16),512);assert.equal(asset.readUInt32BE(20),512);assert.deepEqual(expected,[{src:'https://example.test/sukun/assets/branding/sukun-selected-logo-r1028.png?v=r1028',sizes:'512x512',type:'image/png'}]);});
test('Shared artwork records cannot be mutated by competing writers',()=>{assert(Object.isFrozen(context.window.SukunMediaArtworkR1028));assert(Object.isFrozen(context.window.SukunMediaArtworkR1028[0]));});
test('Favicon fallback points to selected artwork, never the old data star',()=>{assert.match(html,/<link href="\.\/assets\/branding\/sukun-selected-logo-r1028\.png\?v=r\d+" rel="icon" type="image\/png" sizes="512x512"\/>/);assert(!/<link href="data:image\/png;base64,[^"]+" rel="icon"/.test(html));});
test('Intro and system player select the same uncropped original artwork',()=>{const m=html.match(/<div id="sukun-auto-intro"[^>]*>([\s\S]*?)<script id="sukun-auto-intro-clock">/)[1];assert.match(m,/src="\.\/assets\/branding\/sukun-selected-logo-r1028\.png\?v=r\d+"/);assert(!/apMuhur|sukun-logo-existing|<button|dokun/.test(m));});
test('New artwork filename avoids old optional-art cache keys',()=>{assert(artworkPath.includes('r1028'));assert(!artworkPath.includes('sukun-logo-existing'));});
function objects(source){const out=[];for(const match of source.matchAll(/new MediaMetadata\(/g)){let start=match.index+match[0].length;assert.equal(source[start],'{');let depth=0,quote='',escape=false,end=start;for(;end<source.length;end++){const ch=source[end];if(quote){if(escape){escape=false;continue;}if(ch==='\\'){escape=true;continue;}if(ch===quote)quote='';continue;}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue;}if(ch==='{')depth++;if(ch==='}'&&--depth===0){end++;break;}}out.push(source.slice(start,end));}return out;}
const objectsByFile=[['main',objects(html)],['tekke',objects(runtime)]];
test('All seven active metadata writer objects carry explicit artwork',()=>{assert.equal(objectsByFile[0][1].length,6);assert.equal(objectsByFile[1][1].length,1);for(const [,objs] of objectsByFile)for(const o of objs)assert(o.startsWith('{artwork:window.SukunMediaArtworkR1028,'));});
for(const [name,objs] of objectsByFile)objs.forEach((o,i)=>test(name+' MediaMetadata writer '+(i+1)+' preserves metadata and uses selected artwork',()=>{
 const fields=[];const c={window:{SukunMediaArtworkR1028:context.window.SukunMediaArtworkR1028,I18N:{t:x=>x},R170:{Player:{name:'Fixture'}}},MediaMetadata:class{constructor(value){fields.push(value);return value;}},sonBaslik:'Fixture',title:'Fixture',mode:'recording',moduleTitle:'Fixture',P:{name:'Fixture'},s:{id:'fixture',title:'Fixture'},n:{id:'fixture',sectionTitle:'Fixture',moduleTitle:'Fixture',title:'Fixture',queue:[],meta:{}},options:{title:'Fixture'},stepTitle:()=> 'Fixture',translate:x=>x};
 vm.runInNewContext('new MediaMetadata('+o+')',c);const current=fields.pop();assert.deepEqual(JSON.parse(JSON.stringify(current.artwork)),expected);
 vm.runInNewContext('new MediaMetadata('+o.replace('artwork:window.SukunMediaArtworkR1028,','')+')',c);const prior=fields.pop();const copy={...current};delete copy.artwork;assert.deepEqual(JSON.parse(JSON.stringify(copy)),JSON.parse(JSON.stringify(prior)));
}));
const report={total:results.length,passed:results.filter(x=>x.passed).length,results,scope:'Exact selected PNG and all seven shipped MediaMetadata object expressions in VM. No physical Android notification rendering or microphone/audio test.'};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
