'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=process.argv[2]||path.resolve(__dirname,'../..');
const runtime=fs.readFileSync(path.join(root,'assets/runtime/recording-continuity-r1016.js'),'utf8');
const KEY='sukun.recording.continuity.v1',results=[];
const plain=v=>JSON.parse(JSON.stringify(v));
const ticks=async()=>{for(let i=0;i<30;i++)await Promise.resolve()};
function environment(config={},shared=new Map()){
  let clock=1800000000000,id=0,dbCloses=0,dbAborts=0,opens=0,cursorReads=0,valueReads=0,keyReads=0,payloadReads=0,writes=0,storageWrites=0;
  const timers=new Map(),pending=[],events={};
  const q=fn=>queueMicrotask(fn);
  function later(fn){if(config.hold)pending.push(fn);else q(fn)}
  const values=config.values||[new Blob(['1234']),new Blob(['123456'])];
  const indexedDB=config.noIDB?null:{
    ...(config.noDatabases?{}:{databases:()=>config.databasesReject?Promise.reject(Error('private text')):config.databasesHang?new Promise(()=>{}):Promise.resolve(config.missingDB?[]:[{name:'sukunRec',version:1}])}),
    open(name,...args){opens++;assert.equal(name,'sukunRec');assert.equal(args.length,0);if(config.openThrow)throw Error('user private secret');
      const req={transaction:{abort(){dbAborts++;q(()=>req.onerror?.({target:req}))}}};
      later(()=>{
        if(config.missingDB&&config.noDatabases){req.onupgradeneeded?.({target:req});return}
        if(config.blocked){req.onblocked?.();return}
        if(config.openError){req.error=Object.assign(Error('private recording name https://secret/?key=private'),{name:config.errorName||'Error'});req.onerror?.();return}
        const db={objectStoreNames:{contains:name=>name==='clips'&&!config.missingStore},close(){dbCloses++},createObjectStore(){writes++;throw Error('unexpected schema write')},transaction(name,mode){
          assert.equal(name,'clips');assert.equal(mode,'readonly');
          if(config.txThrow)throw Error('secret');
          let aborted=false,index=0;
          const tx={abort(){if(aborted)return;aborted=true;dbAborts++;q(()=>tx.onabort?.())},objectStore(name){assert.equal(name,'clips');return {put(){writes++},delete(){writes++},clear(){writes++},openCursor(){cursorReads++;const c={};
            function step(){
              if(aborted)return;
              if(config.readError){c.onerror?.();return}
              if(config.txAbort){tx.onabort?.();return}
              if(config.txError){tx.onerror?.();return}
              if(index<values.length){const v=values[index++];c.result={get value(){valueReads++;return v},get key(){keyReads++;throw Error('identifier read')},get primaryKey(){keyReads++;throw Error('identifier read')},continue(){later(step)}};c.onsuccess?.()}
              else{c.result=null;c.onsuccess?.();if(config.beforeCommit)config.beforeCommit();if(!config.noComplete)later(()=>tx.oncomplete?.())}
            }
            later(step);return c;
          }}}};return tx;
        }};
        req.result=db;req.onsuccess?.({target:req});
      });return req;
    }
  };
  class RestrictedBlob extends Blob {arrayBuffer(){payloadReads++;throw Error('payload read')}text(){payloadReads++;throw Error('payload read')}stream(){payloadReads++;throw Error('payload read')}slice(){payloadReads++;throw Error('payload read')}}
  const window={indexedDB,crypto:config.noCrypto?undefined:{getRandomValues(a){a.forEach((_,i)=>a[i]=(i+7)%256);return a}},localStorage:{getItem(k){if(config.storageReadThrow)throw Error('secret');return shared.get(k)??null},setItem(k,v){storageWrites++;if(config.storageWriteThrow)throw Error('secret');shared.set(k,v)},removeItem(){writes++}},addEventListener(type,fn){(events[type]??=[]).push(fn)}};
  const context=vm.createContext({window,Blob,Uint8Array,console,Date:{now:()=>clock},setTimeout(fn,ms){const t=++id;timers.set(t,{fn,at:clock+ms});return t},clearTimeout:t=>timers.delete(t)});
  vm.runInContext(runtime,context,{filename:'recording-continuity-r1016.js'});
  const api=window.SukunRecordingUpdateDiagnostics;
  return {api,shared,window,config,context,async drain(){config.hold=false;while(pending.length){pending.shift()();await ticks()}await ticks()},async advance(ms){clock+=ms;for(const [t,v]of [...timers])if(v.at<=clock){timers.delete(t);v.fn()}await ticks()},stats:()=>({dbCloses,dbAborts,opens,cursorReads,valueReads,keyReads,payloadReads,writes,storageWrites}),snapshot:()=>plain(api.snapshot()),RestrictedBlob};
}
async function before(e,options={}){const ticket=await e.api.prepareBeforeUpdate({appVersion:'r1016',controllerVersion:'r1017',targetVersion:'r1017',...options});if(ticket)e.api.commitBeforeReload(ticket);return ticket}
async function test(name,fn){await fn();results.push({name,status:'PASS'})}
module.exports={environment,before,ticks,plain,root,runtime};
if(require.main===module)(async()=>{
  await test('First install captures only a baseline, never invents BEFORE',async()=>{const e=environment();await e.api.afterBoot({appVersion:'r1016',controllerVersion:'r1016'});const s=e.snapshot();assert.equal(s.status,'baseline');assert.equal(s.before,null);assert.equal(s.after.count,2);assert.equal(s.after.blobBytes,10);assert.equal(s.comparison.status,'not-ready');assert.equal(s.after.correlationId,null)});
  await test('Successful empty store is real zero',async()=>{const e=environment({values:[]});await before(e);assert.equal(e.snapshot().before.count,0);assert.equal(e.snapshot().before.blobBytes,0)});
  for(const [name,config,code]of[
    ['No IndexedDB',{noIDB:true},'idb-unavailable'],['Absent database enumeration',{missingDB:true},'db-missing'],['Absent database abort fallback',{missingDB:true,noDatabases:true},'db-missing'],['Missing clips store',{missingStore:true},'store-missing'],['Open throws',{openThrow:true},'db-open-failed'],['Open errors',{openError:true},'db-open-failed'],['Blocked open',{blocked:true},'db-blocked'],['Database enumeration rejects',{databasesReject:true},'db-open-failed'],['Transaction creation fails',{txThrow:true},'read-failed'],['Cursor read fails',{readError:true},'read-failed'],['Transaction aborts',{txAbort:true},'read-aborted'],['Transaction errors',{txError:true},'read-failed'],['Invalid non-Blob record',{values:[{name:'private'}]},'invalid-record']]){
    await test(name+' keeps totals unknown',async()=>{const e=environment(config);await before(e);const s=e.snapshot();assert.equal(s.before.status,'unavailable');assert.equal(s.before.errorCode,code);assert.equal(s.before.count,null);assert.equal(s.before.blobBytes,null);assert.equal(e.stats().writes,0);if(config.missingDB&&!config.noDatabases)assert.equal(e.stats().opens,0);if(config.missingDB&&config.noDatabases)assert.equal(e.stats().dbAborts,1)});
  }
  await test('Cursor exhaustion is not a commit',async()=>{const e=environment({noComplete:true});const task=before(e);await ticks();assert.equal(e.snapshot().before,null);await e.advance(8000);await task;assert.equal(e.snapshot().before.errorCode,'read-timeout');assert.equal(e.snapshot().before.count,null);assert.equal(e.stats().dbAborts,1)});
  await test('Enumeration timeout never starts a late read',async()=>{const e=environment({databasesHang:true});const task=before(e);await e.advance(8000);await task;assert.equal(e.snapshot().before.errorCode,'read-timeout');assert.equal(e.stats().opens,0)});
  await test('Timeout closes late open without scan or write',async()=>{const e=environment({hold:true});const task=before(e);await ticks();await e.advance(8000);await task;await e.drain();assert.equal(e.stats().dbCloses,1);assert.equal(e.stats().cursorReads,0);assert.equal(e.snapshot().before.errorCode,'read-timeout')});
  await test('Only size metadata inspected, never keys or audio bytes',async()=>{const e=environment();await before(e);assert.deepEqual([e.stats().keyReads,e.stats().payloadReads,e.stats().writes],[0,0,0]);assert.equal(e.stats().valueReads,2);assert.equal(e.stats().dbCloses,1);assert(!/\.arrayBuffer\(|\.text\(|\.stream\(|FileReader|\.key\b|primaryKey|fetch\(|XMLHttpRequest|sendBeacon|\.put\(|store\.delete\(|createObjectStore\(/.test(runtime))});
  await test('Cancelled request cannot persist a pending receipt',async()=>{let active=true;const e=environment({hold:true});const task=before(e,{isCurrent:()=>active});await ticks();active=false;await e.drain();await task;assert.equal(e.stats().storageWrites,0);assert.equal(e.snapshot().before,null)});
  await test('Commit rechecks cancellation even after completed read',async()=>{let active=true;const e=environment();const ticket=await e.api.prepareBeforeUpdate({appVersion:'r1016',targetVersion:'r1017',isCurrent:()=>active});active=false;assert.equal(e.api.commitBeforeReload(ticket),false);assert.equal(e.stats().storageWrites,0)});
  await test('Abandoned ticket cannot commit later',async()=>{const e=environment();const ticket=await e.api.prepareBeforeUpdate({appVersion:'r1016',targetVersion:'r1017'});e.api.abandonPrepared();assert.equal(e.api.commitBeforeReload(ticket),false);assert.equal(e.stats().storageWrites,0)});
  await test('A successful pair correlates update only once',async()=>{const e=environment();await before(e);const id=e.snapshot().before.correlationId;const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017',controllerVersion:'r1017'});const s=next.snapshot();assert.equal(s.status,'same');assert.equal(s.after.correlationId,id);assert.equal(s.comparison.causality,'not-determined');await next.api.afterBoot({appVersion:'r1017'});assert.equal(next.stats().opens,1)});
  await test('Mismatch establishes different totals, never deletion causality',async()=>{const e=environment();await before(e);const next=environment({values:[]},e.shared);await next.api.afterBoot({appVersion:'r1017',controllerVersion:'r1017'});const s=next.snapshot();assert.equal(s.status,'different');assert.equal(s.comparison.countDelta,-2);assert.equal(s.comparison.blobBytesDelta,-10);assert.equal(s.comparison.causality,'not-determined')});
  await test('After read failure cannot compare to zero',async()=>{const e=environment();await before(e);const next=environment({readError:true},e.shared);await next.api.afterBoot({appVersion:'r1017'});assert.equal(next.snapshot().status,'unavailable');assert.equal(next.snapshot().after.count,null);assert.equal(next.snapshot().comparison.countDelta,null)});
  await test('Before read failure cannot produce verified comparison',async()=>{const e=environment({readError:true});await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017'});assert.equal(next.snapshot().status,'unavailable');assert.equal(next.snapshot().comparison.status,'unavailable')});
  await test('Same-page afterBoot cannot consume newly staged BEFORE',async()=>{const e=environment();await before(e);await e.api.afterBoot({appVersion:'r1017'});assert.equal(e.snapshot().after,null);assert.equal(e.stats().storageWrites,1)});
  await test('Wrong application build cannot consume pending pair',async()=>{const e=environment();await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1016'});assert.equal(next.snapshot().status,'not-relevant');assert.equal(next.stats().opens,0);assert.equal(next.snapshot().after,null)});
  await test('Stale pair not used as upgrade evidence',async()=>{const e=environment();await before(e);const next=environment({},e.shared);await next.advance(86400001);await next.api.afterBoot({appVersion:'r1017'});assert.equal(next.snapshot().errorCode,'stale-receipt');assert.equal(next.stats().opens,0)});
  await test('Completed pair survives same-version reload without scanning',async()=>{const e=environment();await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017',controllerVersion:'r1017'});const saved=e.shared.get(KEY);const reload=environment({values:[]},e.shared);await reload.api.afterBoot({appVersion:'r1017'});assert.equal(reload.stats().opens,0);assert.equal(e.shared.get(KEY),saved);assert.equal(reload.snapshot().status,'same')});
  await test('Failed local persistence is not verified evidence',async()=>{const e=environment({storageWriteThrow:true});await before(e);assert.equal(e.snapshot().status,'unavailable');assert.equal(e.snapshot().persistence,'unavailable');assert.equal(e.snapshot().comparison.status,'unavailable');assert.equal(e.shared.size,0)});
  await test('Failed local read never produces a baseline or comparison',async()=>{const e=environment({storageReadThrow:true});await e.api.afterBoot({appVersion:'r1016'});assert.equal(e.snapshot().status,'unavailable');assert.equal(e.stats().opens,0)});
  await test('Pair retention is one bounded ASCII metadata record',async()=>{const e=environment();for(let i=0;i<12;i++)await before(e);assert.equal(e.shared.size,1);assert(e.shared.get(KEY).length<=2048);assert(!e.shared.get(KEY).includes('private'));assert.equal(e.stats().storageWrites,12)});
  await test('Snapshot detached and deeply frozen',async()=>{const e=environment();await before(e);const s=e.api.snapshot();assert(Object.isFrozen(s));assert(Object.isFrozen(s.before));assert(Object.isFrozen(s.comparison));assert.throws(()=>{s.before.count=900});assert.equal(e.snapshot().before.count,2)});
  await test('Persisted arbitrary fields and unsafe versions never leak',async()=>{const e=environment();await before(e);const p=JSON.parse(e.shared.get(KEY));p.before.name='private';p.before.controllerVersion='https://secret.test/?key=private';p.secret='private';e.shared.set(KEY,JSON.stringify(p));const next=environment({},e.shared);assert(!JSON.stringify(next.snapshot()).includes('private'));assert.equal(next.snapshot().before.controllerVersion,null)});
  await test('Invalid receipts unavailable, never mistaken for absent history',async()=>{const store=new Map([[KEY,'{"secret":"private"}']]);const e=environment({},store);await e.api.afterBoot({appVersion:'r1016'});assert.equal(e.snapshot().errorCode,'invalid-receipt');assert.equal(e.stats().opens,0);assert(!JSON.stringify(e.snapshot()).includes('private'))});
  await test('No crypto means no persistent user-derived correlation ID',async()=>{const e=environment({noCrypto:true});await before(e);assert.equal(e.snapshot().before.correlationId,null)});
  await test('A concurrent newer receipt prevents stale after-write',async()=>{const e=environment();await before(e);const next=environment({hold:true},e.shared);const task=next.api.afterBoot({appVersion:'r1017'});await ticks();e.shared.set(KEY,'changed by another approved update');await next.drain();await task;assert.equal(next.stats().storageWrites,0);assert.equal(next.snapshot().errorCode,'changed-receipt')});
  for(const name of ['SecurityError','UnknownError','QuotaExceededError','VersionError','AbortError','NotFoundError','InvalidStateError','DataError','TransactionInactiveError','ConstraintError','InvalidAccessError','NotReadableError'])await test(name+' retained without message or stack',async()=>{const e=environment({openError:true,errorName:name});await before(e);assert.equal(e.snapshot().before.errorCode,name);assert(!JSON.stringify(e.snapshot()).includes('private'))});
  await test('Arbitrary error name cannot leak into metadata',async()=>{const e=environment({openError:true,errorName:'private-key-https://secret'});await before(e);assert.equal(e.snapshot().before.errorCode,'db-open-failed');assert(!JSON.stringify(e.snapshot()).includes('private'))});
  await test('Null correlation prevents a paired same/different assertion',async()=>{const e=environment({noCrypto:true});await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017'});assert.equal(next.snapshot().status,'unavailable');assert.equal(next.snapshot().errorCode,'correlation-unavailable')});
  await test('Completed old pair becomes not relevant on a later app build',async()=>{const e=environment();await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017'});const later=environment({},e.shared);await later.api.afterBoot({appVersion:'r1018'});assert.equal(later.snapshot().status,'not-relevant');assert.equal(later.snapshot().errorCode,'build-mismatch');assert.equal(later.stats().opens,0)});
  await test('Expired completed pair is historical, not a fresh verification',async()=>{const e=environment();await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017'});const later=environment({},e.shared);await later.advance(86400001);await later.api.afterBoot({appVersion:'r1017'});assert.equal(later.snapshot().status,'not-relevant');assert.equal(later.snapshot().errorCode,'stale-receipt')});
  await test('Same-app fabricated update pair is rejected',async()=>{const e=environment();await before(e);const p=JSON.parse(e.shared.get(KEY));p.before.targetVersion='r1016';e.shared.set(KEY,JSON.stringify(p));const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1016'});assert.equal(next.snapshot().status,'unavailable');assert.equal(next.snapshot().errorCode,'invalid-receipt')});
  await test('Wrong post-update controller cannot report matched totals',async()=>{const e=environment();await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017',controllerVersion:'r9999'});assert.equal(next.snapshot().status,'not-relevant');assert.equal(next.snapshot().errorCode,'build-mismatch')});
  await test('Legacy r657 global coexists in both script orders',async()=>{for(const legacyFirst of [true,false]){const e=environment();const code=fs.readFileSync(path.join(root,'index.html'),'utf8').match(/window\.SukunRecordingContinuity=Object\.freeze\(\{version:'r657',snapshot:[^\n]+/)[0];e.context.R657_CONTINUITY={};vm.runInContext(code,e.context);if(legacyFirst)vm.runInContext(runtime,e.context);assert.equal(e.window.SukunRecordingContinuity.version,'r657');assert.equal(e.window.SukunRecordingUpdateDiagnostics.version,'r1016')}});
  await test('Ancient BEFORE plus fresh AFTER cannot pass a comparison',async()=>{const e=environment();await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017',controllerVersion:'r1017'});const p=JSON.parse(e.shared.get(KEY));p.before.at-=86400001;e.shared.set(KEY,JSON.stringify(p));const later=environment({},e.shared);await later.api.afterBoot({appVersion:'r1017',controllerVersion:'r1017'});assert.equal(later.snapshot().status,'not-relevant');assert.equal(later.snapshot().errorCode,'stale-receipt')});
  await test('Interrupted first baseline explicitly records unknown measurement',async()=>{let active=true;const e=environment({hold:true});const task=e.api.afterBoot({appVersion:'r1016',isCurrent:()=>active});await ticks();active=false;await e.drain();await task;assert.equal(e.snapshot().status,'unavailable');assert.equal(e.snapshot().after.errorCode,'update-cancelled');assert.equal(e.snapshot().after.count,null)});
  await test('Interrupted AFTER does not remain an indefinite pending pair',async()=>{const e=environment();await before(e);let active=true;const next=environment({hold:true},e.shared);const task=next.api.afterBoot({appVersion:'r1017',controllerVersion:'r1017',isCurrent:()=>active});await ticks();active=false;await next.drain();await task;assert.equal(next.snapshot().status,'unavailable');assert.equal(next.snapshot().after.errorCode,'update-cancelled')});
  await test('Unknown post-update controller prevents comparison certainty',async()=>{const e=environment();await before(e);const next=environment({},e.shared);await next.api.afterBoot({appVersion:'r1017'});assert.equal(next.snapshot().status,'unavailable');assert.equal(next.snapshot().errorCode,'build-mismatch')});
  console.log(JSON.stringify({status:'PASS',total:results.length,passed:results.length,failed:0,scenarios:results,limits:['Controlled IndexedDB and storage events; no physical-device or real browser quota/eviction behavior measured.']},null,2));
})().catch(error=>{console.error(error);process.exitCode=1});
