'use strict';
// Full production collector/presenter, synthetic cached receipts only. No real data.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..'));
const collector=fs.readFileSync(path.join(root,'assets/runtime/health-r940.js'),'utf8');
const presenter=fs.readFileSync(path.join(root,'assets/runtime/health-view-r943.js'),'utf8');
const plain=x=>JSON.parse(JSON.stringify(x));
const freeze=x=>{if(x&&typeof x==='object'){Object.values(x).forEach(freeze);Object.freeze(x);}return x;};
const receipt=(count=3,blobBytes=2048,overrides={})=>({appVersion:'r1015',controllerVersion:'r1015',targetVersion:'r1016',status:'ok',count,blobBytes,errorCode:null,at:1791200000000,correlationId:'b'.repeat(32),...overrides});
const pair=(status='same',overrides={})=>({version:'r1016',status,persistence:'available',errorCode:null,before:receipt(),after:receipt(status==='different'?2:3,status==='different'?1024:2048,{appVersion:'r1016',controllerVersion:'r1016'}),comparison:{status,countDelta:status==='different'?-1:0,blobBytesDelta:status==='different'?-1024:0,causality:'not-determined'},...overrides});
function harness(data=pair(),lang='en'){
 let cached=data,timerId=0;
 const actions={},store=new Map(),blobs=[],downloads=[],timers=new Map();
 const hit=key=>actions[key]=(actions[key]||0)+1,deny=key=>()=>{hit(key);throw Error('Forbidden '+key);};
 class URLApi extends URL{static createObjectURL(blob){hit('blob');blobs.push(blob);return 'blob:synthetic';}static revokeObjectURL(){hit('revoke');}}
 const c={console,URL:URLApi,TextEncoder,TextDecoder,Blob,JSON,Math,Date,Promise,AbortController,DOMException,Uint8Array,
  navigator:{onLine:false,serviceWorker:{controller:null,addEventListener(){}}},location:{href:'https://fixture.invalid/nero.html',origin:'https://fixture.invalid'},performance:{now:()=>100,getEntriesByType:()=>[]},
  document:{readyState:'loading',hidden:false,wasDiscarded:false,querySelector(s){hit('dom');return s==='meta[name="sukun-build"]'?{content:'r1016'}:null;},getElementById(){hit('dom');return null;},querySelectorAll:deny('scan'),addEventListener(){},createElement(tag){hit('create');assert.equal(tag,'a');return{click(){hit('click');downloads.push(this.download);},remove(){hit('remove');}};},body:{append(){hit('append');}}},
  localStorage:{getItem(k){hit('storageRead');return store.get(k)||null;},setItem(k,v){hit('storageWrite');store.set(k,String(v));}},
  sessionStorage:{getItem(k){hit('storageRead');return store.get(k)||null;},setItem(k,v){hit('storageWrite');store.set(k,String(v));}},
  indexedDB:{open:deny('dbOpen'),databases:deny('dbList'),deleteDatabase:deny('dbDelete')},
  fetch:deny('network'),setTimeout(fn,ms){hit('timer');timers.set(++timerId,{fn,ms});return timerId;},clearTimeout(id){timers.delete(id);},setInterval:deny('interval'),requestAnimationFrame:deny('raf'),addEventListener(){},
  SukunRecordingUpdateDiagnostics:{snapshot(){hit('snapshot');return cached;},beforeUpdate:deny('collect'),afterUpdate:deny('collect')},
  SukunRecordingContinuity:{snapshot:deny('legacyAudio'),resume:deny('legacyAudio')},
  SukunRecordingPreparation:{prepare:deny('prepare')},SukunAIRouter:{complete:deny('ai')},I18N:{lang}};
 c.window=c;vm.createContext(c);vm.runInContext(collector,c,{filename:'health-r940.js'});vm.runInContext(presenter,c,{filename:'health-view-r943.js'});Object.keys(actions).forEach(k=>actions[k]=0);
 return {c,actions,store,blobs,downloads,timers,api:c.SukunHealthR940,view:c.SukunHealthViewR943,set:v=>cached=v};
}
// Reuse the unchanged modeled DOM fixture, without running its original suite.
const fixtureFile=path.join(__dirname,'recovered/health_ui_audit.cjs');
const fixtureSource=fs.readFileSync(fixtureFile,'utf8');
const uiHarness=new Function('require','__dirname','process',fixtureSource.slice(0,fixtureSource.indexOf('const clone='))+'\nreturn harness;')(require,path.dirname(fixtureFile),{argv:['node',fixtureFile,root],env:{}});
const row=r=>r.checks.find(x=>x.code==='RECORDING_CONTINUITY');
const presented=(h,r)=>h.view.summarize(r).areas.find(x=>x.id==='storage').checks.find(x=>x.code==='RECORDING_CONTINUITY');
function passive(h){for(const key of ['storageRead','storageWrite','dbOpen','dbList','dbDelete','network','collect','prepare','ai','legacyAudio','timer','interval','raf','dom','scan','create'])assert.equal(h.actions[key]||0,0,key+' must remain passive');}
const results=[];
async function test(name,fn){try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.stack});}}
(async()=>{
 await test('cached snapshot is copied once; read and presenter are passive',()=>{const input=freeze(pair()),old=JSON.stringify(input),h=harness(input),r=h.api.read();h.view.summarize(r);h.view.plainReport(r);h.view.aiPayload(r);assert.equal(h.actions.snapshot,1);assert.equal(JSON.stringify(input),old);assert.equal(row(r).status,'OBSERVED');assert.equal(r.current.recordingContinuity.before.count,3);assert.equal(r.lastRun,null);passive(h);});
 await test('new update API coexists with legacy audio continuity without calling or replacing it',()=>{const h=harness(),legacy=h.c.SukunRecordingContinuity,snapshot=legacy.snapshot;h.api.read();assert.equal(h.c.SukunRecordingContinuity,legacy);assert.equal(h.c.SukunRecordingContinuity.snapshot,snapshot);assert.equal(h.actions.legacyAudio||0,0);delete h.c.SukunRecordingUpdateDiagnostics;assert.equal(h.api.read().current.recordingContinuity,null);assert.equal(h.actions.legacyAudio||0,0);passive(h);});
 await test('same totals remain observation, never successful content verification',()=>{const h=harness(),r=h.api.read(),v=presented(h,r);assert.equal(v.status,'OBSERVED');assert.match(v.detail,/Counts and aggregate sizes match; content equality is unverified/);assert(!/recovered|deleted|lost/i.test(v.detail));passive(h);});
 await test('count mismatch warns without attributing update deletion',()=>{const h=harness(pair('different')),r=h.api.read(),v=presented(h,r);assert.equal(row(r).status,'WARN');assert.equal(v.status,'WARN');assert.match(v.detail,/Counts differ; cause not established/);assert.equal(r.current.recordingContinuity.comparison.countDelta,-1);assert(!/update deleted|update caused|recovered/i.test(v.detail));passive(h);});
 await test('byte-only mismatch does not falsely claim counts differ',()=>{const h=harness(pair('different',{after:receipt(3,1000)})),r=h.api.read(),v=presented(h,r);assert.equal(v.status,'WARN');assert.match(v.detail,/Aggregate sizes differ; cause not established/);assert(!v.detail.includes('Counts differ'));assert.equal(r.current.recordingContinuity.comparison.countDelta,0);passive(h);});
 await test('successful empty reads render real zero count and zero bytes',()=>{const h=harness(pair('same',{before:receipt(0,0),after:receipt(0,0)})),r=h.api.read(),v=presented(h,r);assert.equal(row(r).evidence.before.count,0);assert.equal(row(r).evidence.after.blobBytes,0);assert.equal(v.status,'OBSERVED');assert.match(v.detail,/Before: 0 recordings · 0 bytes; After: 0 recordings · 0 bytes/);passive(h);});
 for(const state of ['none','pending','unavailable','not-relevant'])await test(state+' stays unknown with truthful fixed status copy',()=>{const h=harness(pair(state,{before:state==='none'?null:receipt(),after:null,comparison:{status:state==='pending'?'not-ready':state}})),r=h.api.read(),v=presented(h,r);assert.equal(row(r).status,'NOT_MEASURED');assert.equal(v.status,'NOT_MEASURED');const expected={none:/No local observation yet/,pending:/next observation is pending/,unavailable:/result is unknown/,'not-relevant':/not suitable for an update comparison/};assert.match(v.detail,expected[state]);passive(h);});
 await test('first-install baseline is observed with unknown before-update comparison',()=>{const h=harness(pair('baseline',{before:null,after:receipt(0,0),comparison:{status:'not-ready'}})),r=h.api.read(),v=presented(h,r);assert.equal(row(r).status,'OBSERVED');assert.equal(v.status,'OBSERVED');assert.match(v.detail,/Baseline: 0 recordings · 0 bytes/);assert.equal(v.label,'Initial recording baseline');assert.match(v.detail,/Last saved observation; not a current inventory scan/);assert.match(v.detail,/before-update comparison is unknown/);assert.equal(r.current.recordingContinuity.comparison.countDelta,null);passive(h);});
 const errors=['idb-unavailable','db-missing','store-missing','db-blocked','db-open-failed','read-failed','read-aborted','read-timeout','invalid-record','unsafe-total','storage-unavailable','invalid-receipt','stale-receipt','build-mismatch','changed-receipt','update-cancelled','SecurityError','UnknownError','QuotaExceededError','VersionError','AbortError','NotFoundError','InvalidStateError','DataError','TransactionInactiveError','ConstraintError','InvalidAccessError','NotReadableError','correlation-unavailable'];
 for(const errorCode of errors)await test(errorCode+' failure never becomes empty successful storage',()=>{const h=harness(pair('unavailable',{errorCode,after:receipt(0,0,{status:'unavailable',errorCode}),comparison:{status:'unavailable'}})),r=h.api.read(),v=presented(h,r);assert.equal(row(r).evidence.after.count,null);assert.equal(row(r).evidence.after.blobBytes,null);assert.equal(v.status,'NOT_MEASURED');assert.match(v.detail,/After: recording count and size unknown/);assert(!v.detail.includes('After: 0 recordings'));assert.equal(row(r).evidence.errorCode,errorCode);passive(h);});
 await test('malicious/unrecognized fields are excluded from current, plain and technical report',async()=>{const secret='PRIVATE_SENTINEL',input=pair('different');input.secret=secret;input.history=Array(200).fill({name:secret});input.version=secret;input.errorCode=secret;input.comparison.causality=secret;input.comparison.path='https://'+secret;for(const key of ['before','after'])Object.assign(input[key],{key:secret,name:secret,url:'blob:'+secret,audio:secret,message:secret,correlationId:secret,errorCode:secret,controllerVersion:secret});const h=harness(input),r=h.api.read(),json=JSON.stringify(r);assert(!json.includes(secret));assert(!json.includes('correlationId'));assert(!json.includes('history'));assert.equal(row(r).evidence.comparison.causality,'not-determined');assert(!h.view.plainReport(r).includes(secret));assert(!JSON.stringify(h.view.summarize(r)).includes(secret));passive(h);});
 await test('only fixed fields and the latest pair are retained in the report',()=>{const input=pair();input.receipts=Array(10000).fill(receipt());input.before.history=Array(1000).fill(receipt());const h=harness(input),r=h.api.read(),e=row(r).evidence;assert.deepEqual(Object.keys(e).sort(),['after','before','comparison','errorCode','persistence','status','version']);assert.deepEqual(Object.keys(e.before).sort(),['appVersion','at','blobBytes','controllerVersion','count','errorCode','status','targetVersion']);assert(JSON.stringify(e).length<1200);assert(!JSON.stringify(r.timeline).includes('recordingContinuity'));passive(h);});
 await test('unknown numbers never coerce to zero and malformed comparison cannot pass',()=>{for(const invalid of [null,undefined,'0',false,NaN,Infinity,-1,1.5,Number.MAX_SAFE_INTEGER+1]){const h=harness(pair('same',{after:receipt(0,0,{count:invalid})})),r=h.api.read(),v=presented(h,r);assert.equal(row(r).evidence.after.count,null);assert.equal(row(r).evidence.after.blobBytes,null);assert.equal(row(r).status,'NOT_MEASURED');assert.equal(v.status,'NOT_MEASURED');assert(!v.detail.includes('After: 0 recordings'));passive(h);}});
 await test('missing and throwing owners do not trigger fallback collection',()=>{const absent=harness();delete absent.c.SukunRecordingUpdateDiagnostics;assert.equal(absent.api.read().current.recordingContinuity,null);assert.equal(row(absent.api.read()),undefined);passive(absent);const h=harness();h.c.SukunRecordingUpdateDiagnostics.snapshot=()=>{throw Error('PRIVATE_SENTINEL');};const r=h.api.read();assert.equal(row(r).status,'NOT_MEASURED');assert(!JSON.stringify(r).includes('PRIVATE_SENTINEL'));passive(h);});
 await test('malformed roots, arrays, invalid enums and throwing fields cannot break report',()=>{for(const input of [null,[],[pair()],false,'PRIVATE_SENTINEL',{status:'PRIVATE_SENTINEL',before:[]},Object.defineProperty({},'before',{get(){throw Error('PRIVATE_SENTINEL');}})]){const h=harness(input),r=h.api.read();assert.equal(row(r).status,'NOT_MEASURED');assert(!JSON.stringify(r).includes('PRIVATE_SENTINEL'));const v=presented(h,{checks:[{code:'RECORDING_CONTINUITY',status:'PASS',evidence:input}]});assert.equal(v.status,'NOT_MEASURED');assert(!JSON.stringify(v).includes('PRIVATE_SENTINEL'));passive(h);}});
 await test('presenter independently rejects invalid evidence and ignores supplied PASS',()=>{const h=harness(),e=pair('same',{after:receipt(null,null)}),r={lastRun:{at:1},checks:[{code:'RECORDING_CONTINUITY',status:'PASS',evidence:e}]};assert.equal(presented(h,r).status,'NOT_MEASURED');e.after=receipt(2,1024);assert.equal(presented(h,r).status,'WARN');assert.match(presented(h,r).detail,/Counts differ; cause not established/);passive(h);});
 await test('cancelled observation never claims the application update was cancelled',()=>{for(const lang of ['tr','en']){const h=harness(pair('unavailable',{errorCode:'update-cancelled',after:receipt(null,null,{status:'unavailable',errorCode:'update-cancelled'})}),lang),v=presented(h,h.api.read());assert(v.detail.includes(lang==='tr'?'Gözlem iptal edildi':'Observation cancelled'));assert(!/Update cancelled|Güncelleme iptal edildi/.test(v.detail));passive(h);}});
 await test('contradictory success status with a read error stays unknown',()=>{const h=harness(pair('same',{after:receipt(0,0,{errorCode:'read-failed'})})),r=h.api.read();assert.equal(row(r).status,'NOT_MEASURED');assert.equal(row(r).evidence.after.count,null);assert.equal(presented(h,r).status,'NOT_MEASURED');const supplied={checks:[{code:'RECORDING_CONTINUITY',status:'PASS',evidence:pair('same',{after:receipt(0,0,{errorCode:'SecurityError'})})}]};assert.equal(presented(h,supplied).status,'NOT_MEASURED');passive(h);});
 await test('report refresh uses latest pair without growing event or checkpoint history',()=>{const h=harness(),first=h.api.read(),saved=JSON.stringify([...h.store]);h.set(pair('different'));const next=h.api.read();assert.equal(row(next).status,'WARN');assert.deepEqual(plain(next.timeline),plain(first.timeline));assert.equal(JSON.stringify([...h.store]),saved);assert.equal(h.actions.snapshot,2);passive(h);});
 await test('persistence failure discloses that next-launch evidence may be unavailable',()=>{const h=harness(pair('same',{persistence:'unavailable',errorCode:'storage-unavailable'})),r=h.api.read(),v=presented(h,r);assert.match(v.detail,/could not be retained for the next launch/);assert.match(v.detail,/Local report only; excluded from AI/);passive(h);});
 await test('AI payload is exactly unchanged by local receipts, including aggregate statuses',()=>{const h=harness(),baseline=h.api.read();baseline.checks=baseline.checks.filter(x=>x.code!=='RECORDING_CONTINUITY');const expected=JSON.stringify(h.view.aiPayload(baseline)),key=h.view.reportKey(baseline);for(const state of ['none','pending','baseline','same','different','unavailable','not-relevant']){const r=plain(baseline);r.current.recordingContinuity=pair(state);r.checks.push({code:'RECORDING_CONTINUITY',status:'WARN',evidence:pair(state)});assert.equal(JSON.stringify(h.view.aiPayload(r)),expected,state);assert.equal(h.view.reportKey(r),key,state);assert(!JSON.stringify(h.view.aiPayload(r)).includes('RECORDING_CONTINUITY'));}passive(h);});
 await test('TR and EN presenter use translated fixed labels and status text',()=>{for(const lang of ['tr','en']){const h=harness(pair('different'),lang),r=h.api.read(),v=presented(h,r),txt=h.view.plainReport(r);assert.match(v.label,lang==='tr'?/Son güncellemenin/:/Recording observations for the last update/);assert.match(v.detail,lang==='tr'?/Kayıt sayıları farklı; nedeni belirlenmedi/:/Counts differ; cause not established/);assert.match(txt,lang==='tr'?/Önce: 3 kayıt · 2048 bayt/:/Before: 3 recordings · 2048 bytes/);assert(!/PRIVATE_SENTINEL|\[object Object\]/.test(txt));passive(h);}});
 await test('actual update diagnostics runtime and health agree on persisted synthetic receipt schema',()=>{
  const runtime=fs.readFileSync(path.join(root,'assets/runtime/recording-continuity-r1016.js'),'utf8');
  for(const state of ['same','different','baseline','unavailable']){
   const h=harness(),at=Date.now(),before=state==='baseline'?null:receipt(3,2048,{at}),after=receipt(state==='different'?2:3,state==='different'?1024:2048,{appVersion:'r1016',controllerVersion:'r1016',at,correlationId:state==='baseline'?null:'b'.repeat(32),...(state==='unavailable'?{status:'unavailable',count:null,blobBytes:null,errorCode:'SecurityError'}:{})});
   h.store.set('sukun.recording.continuity.v1',JSON.stringify({schema:1,before,after}));delete h.c.SukunRecordingUpdateDiagnostics;vm.runInContext(runtime,h.c,{filename:'recording-continuity-r1016.js'});Object.keys(h.actions).forEach(k=>h.actions[k]=0);
   const r=h.api.read(),e=row(r).evidence;assert.equal(e.status,state);assert.equal(e.after.count,state==='unavailable'?null:state==='different'?2:3);assert.equal(presented(h,r).status,state==='different'?'WARN':state==='unavailable'?'NOT_MEASURED':'OBSERVED');passive(h);
  }
 });
 for(const lang of ['tr','en'])await test('mounted local report, repeated navigation and AI preview preserve privacy in '+lang,async()=>{
  const h=harness(pair('different'),lang),ui=uiHarness(),view=ui.c.SukunHealthViewR943;let current=h.api.read();
  ui.c.I18N.lang=lang;view.mount(ui.panel,{read:()=>current,close(){}});
  let html=ui.panel.querySelector('[data-health-content]').innerHTML;
  assert(html.includes(lang==='en'?'Counts differ; cause not established':'Kayıt sayıları farklı; nedeni belirlenmedi'));
  assert(html.includes(lang==='en'?'Last saved observation; not a current inventory scan':'Son saklanan gözlem; güncel kayıt taraması değildir'));
  for(let n=0;n<2;n++){await ui.click('report');html=ui.panel.querySelector('[data-health-content]').innerHTML;assert(html.includes('RECORDING_CONTINUITY'));await ui.click('home');}
  h.set(pair('baseline',{before:null,after:receipt(0,0),comparison:{status:'not-ready'}}));current=h.api.read();view.render(ui.panel,current);
  html=ui.panel.querySelector('[data-health-content]').innerHTML;
  assert(html.includes(lang==='en'?'Initial recording baseline':'İlk kayıt gözlemi'));assert(html.includes(lang==='en'?'0 recordings · 0 bytes':'0 kayıt · 0 bayt'));
  await ui.click('explain');await ui.click('ai-preview');html=ui.panel.querySelector('[data-health-content]').innerHTML;
  assert(!html.includes('RECORDING_CONTINUITY'));assert(!html.includes(lang==='en'?'0 recordings · 0 bytes':'0 kayıt · 0 bayt'));
  assert.equal(ui.fetches.length,0);assert.equal(ui.transportCalls.length,0);assert.equal(ui.panel.getAttribute('aria-busy'),'false');passive(h);
 });
 await test('technical export downloads sanitized cached pair with no DB, collection, or network work',async()=>{const input=pair();input.before.name='PRIVATE_SENTINEL';const h=harness(input),r=await h.api.exportReport();assert.equal(h.actions.snapshot,1);assert.equal(h.blobs.length,1);const saved=JSON.parse(await h.blobs[0].text());assert.deepEqual(saved,plain(r));assert.equal(saved.current.recordingContinuity.before.count,3);assert(!JSON.stringify(saved).includes('PRIVATE_SENTINEL'));assert.equal(h.actions.create,1);assert.equal(h.actions.click,1);assert.equal(h.actions.timer,1);assert.deepEqual([...h.timers.values()].map(x=>x.ms),[1000]);for(const key of ['dbOpen','dbList','dbDelete','network','collect','prepare','ai','storageRead','storageWrite','scan'])assert.equal(h.actions[key]||0,0,key);});
 const output={source:root,collectorSha256:crypto.createHash('sha256').update(collector).digest('hex'),presenterSha256:crypto.createHash('sha256').update(presenter).digest('hex'),scope:'Full production collector and presenter; synthetic cached metadata in isolated VM. No real storage, browser display, audio, update or recovery verification.',passed:results.filter(x=>x.passed).length,total:results.length,results};
 fs.writeFileSync(path.join(__dirname,'recording_continuity_health_results.json'),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));process.exitCode=output.passed===output.total?0:1;
})();
