'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {environment,ticks,root}=require('./recording_continuity_contract.cjs');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),start=html.indexOf('/* r921: controller, registered active worker and waiting update have distinct identities. */');
const source=html.slice(start,html.indexOf('</script>',start));
function eventTarget(){const listeners={};return {addEventListener(type,fn){(listeners[type]??=[]).push(fn)},dispatchEvent(e){for(const fn of listeners[e.type]||[])fn(e)}}}
async function setup(options={}){
  const e=environment(),events=eventTarget(),sw=eventTarget(),doc=eventTarget();let maintenance=!!options.maintenance,reloads=0,saves=0,migrations=0,skipWaiting=0;
  const worker=(version,state='activated')=>({version,state,scriptURL:'https://synthetic.test/sukun/sw.js',addEventListener(){},postMessage({type},ports){if(options.statusUnknown&&type==='STATUS')return ports[0].postMessage({complete:true});if(type==='SKIP_WAITING'){skipWaiting++;sw.controller=waiting;reg.waiting=null;waiting.state='activated';sw.dispatchEvent({type:'controllerchange'});ports[0].postMessage({ok:true,v:version,complete:true})}else ports[0].postMessage({v:version,complete:true})}});
  const old=worker('r1016'),waiting=worker('r1017','installed'),reg={scope:'https://synthetic.test/sukun/',active:old,waiting,installing:null,addEventListener(){},update:async()=>{}};
  sw.controller=old;sw.getRegistration=async()=>reg;sw.register=async()=>reg;
  const globals={URL,MessageChannel:class{constructor(){const p1={close(){}},p2={close(){},postMessage(data){queueMicrotask(()=>p1.onmessage?.({data}))}};this.port1=p1;this.port2=p2}},navigator:{serviceWorker:sw},location:{protocol:'https:',href:'https://synthetic.test/sukun/nero.html?v=r1016',reload(){reloads++}},document:{...doc,hidden:false,querySelector:()=>({content:'r1016'}),querySelectorAll:()=>[]},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options?.detail}},addEventListener:events.addEventListener,dispatchEvent:events.dispatchEvent,speechSynthesis:{speaking:false,pending:false},skToast(){}};
  Object.assign(e.context,globals);Object.assign(e.window,globals,{SukunTabOwner:{snapshot:()=>({maintenance})},SukunSessionState:{snapshot:()=>({phase:'IDLE'})},SukunSessionMemory:{save:()=>{saves++},diagnostics:()=>({error:''})},SukunDataMigration:{run:async()=>{migrations++;return {status:'complete'}}}});
  if(options.absentAPI)delete e.window.SukunRecordingUpdateDiagnostics;
  vm.runInContext(source,e.context,{filename:'actual-update-manager.js'});events.dispatchEvent({type:'load'});await ticks();await ticks();
  return {...e,sw,worker,reg,events,manager:e.window.SukunUpdateManager,setMaintenance(value,emit=true){maintenance=value;if(emit)events.dispatchEvent({type:'sukun:tabownerchange'})},counts:()=>({reloads,saves,migrations,skipWaiting}),async flush(){await ticks();await e.advance(0);await ticks()}};
}
const results=[];async function test(name,fn){await fn();results.push({name,status:'PASS'})}
(async()=>{
  await test('Authorized idle update commits BEFORE immediately before one reload',async()=>{const f=await setup();const result=f.manager.activate();await f.flush();await result;assert.equal(f.counts().reloads,1);const s=f.snapshot();assert.equal(s.status,'pending');assert.equal(s.before.appVersion,'r1016');assert.equal(s.before.targetVersion,'r1017');assert.equal(s.before.count,2);assert.equal(s.after,null)});
  await test('No update request only takes baseline and never reloads',async()=>{const f=await setup();assert.equal(f.snapshot().status,'baseline');assert.equal(f.counts().reloads,0);assert.equal(f.counts().skipWaiting,0)});
  await test('Maintenance defers boot measurement and activation until settlement',async()=>{const f=await setup({maintenance:true});assert.equal(f.stats().opens,0);await f.manager.activate();await f.flush();assert.equal(f.counts().reloads,0);assert.equal(f.manager.snapshot().updateQueued,true);f.setMaintenance(false);await f.flush();assert.equal(f.counts().reloads,1);assert.equal(f.snapshot().before.count,2)});
  await test('Queued update cancellation prevents late import completion reload',async()=>{const f=await setup({maintenance:true});await f.manager.activate();await f.flush();assert.equal(f.manager.cancel(),true);f.setMaintenance(false);await f.flush();assert.equal(f.counts().reloads,0);assert.equal(f.counts().skipWaiting,0)});
  await test('Maintenance starting during diagnostic prevents stale receipt and reload',async()=>{const f=await setup();f.config.hold=true;const task=f.manager.activate();await ticks();f.setMaintenance(true);await f.drain();await task;assert.equal(f.counts().reloads,0);assert.equal(f.snapshot().before,null);assert.equal(f.manager.snapshot().updateQueued,true);f.setMaintenance(false);await f.flush();assert.equal(f.counts().reloads,1);assert.equal(f.snapshot().before.count,2)});
  await test('Controller replacement during diagnostic cannot persist old target',async()=>{const f=await setup();f.config.hold=true;const task=f.manager.activate();await ticks();const newController=f.worker('r1018');f.sw.controller=newController;f.sw.dispatchEvent({type:'controllerchange'});await f.drain();await task;await f.flush();assert.equal(f.counts().reloads,1);assert.equal(f.snapshot().before.targetVersion,'r1018');assert.equal(f.snapshot().before.controllerVersion,'r1018')});
  await test('Unknown controller version does not wedge an approved update',async()=>{const f=await setup({statusUnknown:true});const task=f.manager.activate();await f.flush();await task;assert.equal(f.counts().reloads,1);assert.equal(f.snapshot().before,null);assert.equal(f.snapshot().errorCode,'build-mismatch')});
  await test('Failed diagnostic persists unknown totals but approved update proceeds',async()=>{const f=await setup();f.config.readError=true;const task=f.manager.activate();await f.flush();await task;assert.equal(f.counts().reloads,1);assert.equal(f.snapshot().before.status,'unavailable');assert.equal(f.snapshot().before.count,null)});
  await test('Failed local diagnostic persistence never blocks approved reload',async()=>{const f=await setup();f.config.storageWriteThrow=true;const task=f.manager.activate();await f.flush();await task;assert.equal(f.counts().reloads,1);assert.equal(f.snapshot().persistence,'unavailable');assert.equal(f.snapshot().comparison.status,'unavailable')});
  await test('Diagnostic timeout never reports zero and late response cannot reload twice',async()=>{const f=await setup();f.config.hold=true;const task=f.manager.activate();await ticks();await f.advance(8000);await ticks();await task;assert.equal(f.counts().reloads,1);assert.equal(f.snapshot().before.errorCode,'read-timeout');await f.drain();assert.equal(f.counts().reloads,1)});
  await test('Authorization timeout during diagnostic prevents a late reload',async()=>{const f=await setup();f.config.hold=true;const task=f.manager.activate();await ticks();for(let i=0;i<10&&f.stats().opens<2;i++)await ticks();assert.equal(f.manager.snapshot().phase,'saving');await f.advance(32001);await ticks();await task;await f.drain();assert.equal(f.counts().reloads,0);assert.equal(f.snapshot().before,null);assert.equal(f.manager.snapshot().phase,'error')});
  await test('Absent new API preserves prior safe manager behavior',async()=>{const f=await setup({absentAPI:true});const task=f.manager.activate();await f.flush();await task;assert.equal(f.counts().reloads,1)});
  await test('Ordinary microphone-save scope is not silently expanded',async()=>{const f=await setup();f.window.SukunItemRecording={snapshot:()=>({phase:'saving'})};assert.equal(f.manager.snapshot().sessionBusy,false)});
  console.log(JSON.stringify({status:'PASS',total:results.length,passed:results.length,failed:0,scenarios:results,limits:['Actual manager and diagnostic source in controlled VM; no real service worker/browser scheduling, device storage, or microphone measurement.']},null,2));
})().catch(error=>{console.error(error);process.exitCode=1});
