/* Production functions and UI flows in a deterministic modeled DOM. No device playback claim. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.env.SUKUN_HEALTH_SOURCE||path.join(__dirname,'../../..')),collector=fs.readFileSync(root+'/assets/runtime/health-r940.js','utf8'),view=fs.readFileSync(root+'/assets/runtime/health-view-r943.js','utf8'),results=[];
function test(id,fn){return Promise.resolve().then(fn).then(()=>results.push({id,pass:true}));}
function decode(s){return String(s).replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');}
class Node {
 constructor(tag,doc){Object.assign(this,{tagName:tag.toUpperCase(),doc,children:[],dataset:{},attributes:{},style:{},listeners:{},disabled:false,hidden:false,open:false,checked:false,textContent:'',scrollTop:0});this.classList={add:c=>this.attributes.class=((this.attributes.class||'')+' '+c).trim(),contains:c=>(this.attributes.class||'').split(/\s+/).includes(c)};}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=v;if(k==='disabled')this.disabled=true;if(k==='open')this.open=true;if(k==='checked')this.checked=true;if(k==='value')this.value=v;if(k==='content')this.content=v;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);}
 getAttribute(k){return this.attributes[k]??null;}append(...nodes){for(const n of nodes){n.remove();this.children.push(n);n.parentElement=this;}}remove(){if(this.parentElement){this.parentElement.children.splice(this.parentElement.children.indexOf(this),1);this.parentElement=null;}}
 contains(n){return this===n||this.children.some(c=>c.contains(n));}get isConnected(){return this===this.doc.body||this===this.doc.head||this.doc.body?.contains(this)||this.doc.head?.contains(this);}
 all(){return this.children.flatMap(x=>[x,...x.all()]);}matches(selector){return selector.split(',').some(part=>{part=part.trim();if(part.includes(' '))return false;const tag=part.match(/^[a-zA-Z]+/);if(tag&&this.tagName!==tag[0].toUpperCase())return false;const id=part.match(/#([\w-]+)/);if(id&&this.id!==id[1])return false;for(const c of part.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(c[1]))return false;for(const a of part.matchAll(/\[([\w-]+)(?:="([^"]*)")?\]/g)){if(a[1]==='open'){if(!this.open)return false;}else if(!(a[1] in this.attributes)||(a[2]!==undefined&&this.attributes[a[1]]!==a[2]))return false;}return true;});}
 querySelectorAll(s){return this.all().filter(n=>n.matches(s));}querySelector(s){return this.querySelectorAll(s)[0]||null;}closest(s){return this.matches(s)?this:this.parentElement?.closest(s)||null;}
 set innerHTML(html){this._html=html;this.children=[];const stack=[this];for(const m of html.matchAll(/<\/?([a-zA-Z][\w-]*)\b([^>]*)>/g)){if(m[0][1]==='/'){while(stack.length>1){const top=stack.pop();if(top.tagName===m[1].toUpperCase())break;}continue;}const n=new Node(m[1],this.doc);for(const a of m[2].matchAll(/([\w-]+)(?:="([^"]*)")?/g))n.setAttribute(a[1],decode(a[2]??''));stack.at(-1).append(n);if(!['input','br','meta','hr','img'].includes(m[1]))stack.push(n);}}
 get innerHTML(){return this._html||'';}addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);}focus(){this.doc.activeElement=this;}scrollIntoView(){}getClientRects(){return this.isConnected?[{}]:[];}click(){return this.doc.panel?.fire('click',{target:this});}showModal(){this.open=true;}close(){this.open=false;for(const fn of this.listeners.close||[])fn({target:this});}
 async fire(type,e){for(const fn of this.listeners[type]||[])await fn(e);}after(n){this.parentElement?.append(n);}
}
function harness(full=false){
 const timers=new Map(),store=new Map(),eventListeners={},transportCalls=[],fetches=[],c={console,URL,Response,Blob,AbortController,TextDecoder,TextEncoder,Uint8Array,crypto:crypto.webcrypto,Date,Math,JSON,Promise,DOMException};let timerId=0;
 c.setTimeout=(fn,ms)=>{const id=++timerId;timers.set(id,{fn,ms});return id;};c.clearTimeout=id=>timers.delete(id);c.setInterval=()=>{throw Error('unexpected interval')};c.clearInterval=()=>{};
 const d={readyState:'loading',hidden:false,wasDiscarded:false,activeElement:null,listeners:{},createElement:tag=>new Node(tag,d),addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);}};d.body=new Node('body',d);d.head=new Node('head',d);const meta=new Node('meta',d);meta.setAttribute('name','sukun-build');meta.setAttribute('content','r986');d.head.append(meta);d.querySelector=s=>d.head.querySelector(s)||d.body.querySelector(s);d.getElementById=id=>d.body.querySelector('#'+id)||d.head.querySelector('#'+id);c.document=d;
 c.navigator={onLine:true,storage:{estimate:async()=>({usage:100,quota:10000})},serviceWorker:{controller:{postMessage(){transportCalls.push('STATUS');}},addEventListener(){}}};
 c.performance={now:()=>Date.now(),getEntriesByType:()=>[]};c.PerformanceObserver={supportedEntryTypes:[]};c.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};c.location={href:'https://test.invalid/sukun/nero.html',origin:'https://test.invalid'};
 c.fetch=async url=>{fetches.push(url);throw Error('HTTP unavailable')};c.addEventListener=(k,fn)=>(eventListeners[k]??=[]).push(fn);c.dispatch=async(k,detail)=>{for(const fn of eventListeners[k]||[])await fn({detail})};c.I18N={lang:'tr'};c.SukunSessionState={peek:()=>({phase:'paused',activeMode:'esma',count:20,target:100,epoch:7,owner:'user'})};c.SukunSessionMemory={diagnostics:()=>({writes:1,version:'r970',error:''})};c.SukunAIRouter={snapshot:()=>({providers:[],lastResult:null}),hasAnyKey:()=>true};c.window=c;
 for(const name of ['SukunLockAudio','SukunLockJourneyTransportV2','SukunAudioHub','SukunTempoAuthority'])c[name]=new Proxy({snapshot:()=>null,get:()=>1},{get:(o,k)=>k in o?o[k]:(...args)=>transportCalls.push([name,k,args])});
 vm.createContext(c);vm.runInContext(view,c);if(full)vm.runInContext(collector,c);const panel=new Node('details',d);panel.id='r940Health';panel.open=true;d.body.append(panel);d.panel=panel;
 return {c,d,panel,timers,transportCalls,fetches,store,async click(action){const node=panel.querySelector(`[data-health-action="${action}"]`);assert(node,'missing action '+action);await panel.fire('click',{target:node});},async consent(){const input=panel.querySelector('[data-health-consent]');assert(input);input.checked=true;await panel.fire('change',{target:input});}};
}
const clone=x=>JSON.parse(JSON.stringify(x));const basic=()=>({build:'r986',lastRun:{at:100,durationMs:12},checks:[{code:'BUILD',status:'PASS',evidence:{}}],current:{session:{epoch:7}},incidents:[],timeline:[]});
(async()=>{
 function audioReport(reason,transition=false){const r=basic();r.checks.push({code:'AUDIO_CONSISTENCY',status:transition?'OBSERVED':'PASS',evidence:{transition,actualSessionSource:'SILENCE',audibility:'NOT_MEASURED',scope:'transport-state-not-audibility',...(reason==null?{}:{voiceExpectation:{reason,voiceEnabled:reason!=='voice-off',intendedAudible:reason!=='voice-off',readerActive:reason==='reader-running'}})}},{code:'DEVICE_AUDIO',status:'PASS',evidence:{}});return r;}
 const starts={tr:{'voice-off':'Sesli zikir tercihi kapalı','reader-running':'Bir metin okuyucusu etkin','voice-on':'Sesli zikir seçili; son oturum kaydı sessiz tempo gösteriyor'},en:{'voice-off':'Spoken dhikr is switched off','reader-running':'A text reader is active','voice-on':'Spoken dhikr is selected; the latest session record shows silent tempo'}};
 const originalDetail={tr:'Ses kaynaklarının uygulama içindeki uyumu incelendi.',en:'The consistency of audio sources inside the app was examined.'};
 for(const lang of ['tr','en']){
  for(const reason of ['voice-off','reader-running','voice-on'])await test('audio-policy-'+lang+'-'+reason+'-localized-without-false-warning-or-audibility-pass',()=>{
   const h=harness();h.c.I18N.lang=lang;const r=audioReport(reason),summary=h.c.SukunHealthViewR943.summarize(r),area=summary.areas.find(x=>x.id==='audio'),row=area.checks.find(x=>x.code==='AUDIO_CONSISTENCY');
   assert(row.detail.includes(starts[lang][reason]));assert(row.detail.includes(lang==='tr'?'Duyulan ses cihazda dinlenerek doğrulanır.':'Audible sound needs a listening check on the device.'));assert.equal(row.status,'PASS');assert.equal(summary.counts.warning,0);assert.equal(summary.counts.failure,0);assert.equal(summary.areas.find(x=>x.id==='device').checks.find(x=>x.code==='DEVICE_AUDIO').status,'NOT_MEASURED');assert(h.c.SukunHealthViewR943.plainReport(r).includes(row.detail));
  });
  await test('audio-missing-policy-'+lang+'-retains-existing-detail',()=>{const h=harness();h.c.I18N.lang=lang;const r=audioReport(null),row=h.c.SukunHealthViewR943.summarize(r).areas.find(x=>x.id==='audio').checks.find(x=>x.code==='AUDIO_CONSISTENCY');assert.equal(row.detail,originalDetail[lang]);assert.equal(row.status,'PASS');});
  await test('audio-unknown-policy-'+lang+'-retains-existing-detail',()=>{const h=harness();h.c.I18N.lang=lang;const r=audioReport('unknown'),row=h.c.SukunHealthViewR943.summarize(r).areas.find(x=>x.id==='audio').checks.find(x=>x.code==='AUDIO_CONSISTENCY');assert.equal(row.detail,originalDetail[lang]);assert.equal(row.status,'PASS');});
  await test('audio-transition-'+lang+'-still-takes-precedence-over-voice-off-policy',()=>{const h=harness();h.c.I18N.lang=lang;const r=audioReport('voice-off',true),row=h.c.SukunHealthViewR943.summarize(r).areas.find(x=>x.id==='audio').checks.find(x=>x.code==='AUDIO_CONSISTENCY');assert.equal(row.status,'OBSERVED');assert(row.detail.includes(lang==='tr'?'Geçici olabilir; başarılı kontrol olarak işaretlenmedi.':'This may be temporary; it is not marked as a passed check.'));assert(!row.detail.includes(starts[lang]['voice-off']));});
 }
 await test('five-groups-cover-session-memory-and-future-unknown-result',()=>{const h=harness(),r=basic();r.checks.push({code:'SESSION_MEMORY',status:'WARN',evidence:{}},{code:'PRIVATE_ARBITRARY_CODE',status:'FAIL',title:'DO NOT SEND'});const s=h.c.SukunHealthViewR943.summarize(r);assert.equal(s.areas.length,5);assert.equal(s.counts.warning,1);assert.equal(s.counts.failure,1);assert(s.areas[2].checks.some(x=>x.code==='SESSION_MEMORY'));assert.equal(s.status,'FAIL');assert(!JSON.stringify(h.c.SukunHealthViewR943.aiPayload(r)).includes('DO NOT SEND'));assert(!JSON.stringify(h.c.SukunHealthViewR943.aiPayload(r)).includes('PRIVATE_ARBITRARY_CODE'));assert(!JSON.stringify(h.c.SukunHealthViewR943.aiPayload(r)).includes('ADDITIONAL_CHECK'));});
 await test('unrun-deep-check-keeps-file-group-unknown',()=>{const h=harness(),s=h.c.SukunHealthViewR943.summarize(basic());assert.equal(s.areas.find(x=>x.id==='files').status,'NOT_MEASURED');assert(s.counts.unknown>0);});
 await test('device-pass-cannot-promote-physical-audio-to-pass',()=>{const h=harness(),r=basic();r.checks.push({code:'DEVICE_AUDIO',status:'PASS'});r.deviceCheck={responses:{lockedSound:'AS_EXPECTED'}};assert.equal(h.c.SukunHealthViewR943.summarize(r).areas[4].checks.find(x=>x.code==='DEVICE_AUDIO').status,'NOT_MEASURED');});
 await test('missing-memory-and-storage-metrics-remain-unknown',()=>{const h=harness(),r=basic();r.checks.push({code:'HEAP',status:'PASS',evidence:{}},{code:'STORAGE_QUOTA',status:'PASS',evidence:{usage:null,quota:0}});const rows=h.c.SukunHealthViewR943.summarize(r).areas[2].checks;assert.equal(rows.find(x=>x.code==='HEAP').status,'NOT_MEASURED');assert.equal(rows.find(x=>x.code==='STORAGE_QUOTA').status,'NOT_MEASURED');assert(!('activeAudioEngineCount'in h.c.SukunHealthViewR943.aiPayload(r).metrics));});
 await test('english-summary-metrics-history-and-guides-render-in-english',async()=>{const h=harness();h.c.I18N.lang='en';const r=basic();r.checks.push({code:'HEAP',status:'OBSERVED',evidence:{heapBytes:10485760,heapLimit:104857600}},{code:'SESSION_MEMORY',status:'WARN',evidence:{}});h.c.SukunHealthViewR943.mount(h.panel,{read:()=>r});assert.equal(h.panel.getAttribute('data-i18n-owned'),'health-r975');assert(h.panel.querySelector('[data-health-content]').innerHTML.includes('progress'));await h.click('tests');assert(h.panel.querySelector('[data-health-content]').innerHTML.includes('Manual'));await h.click('guide-manual');const html=h.panel.querySelector('[data-health-content]').innerHTML;assert(html.includes('Pause'));assert(!html.includes('duraklat'));const txt=h.c.SukunHealthViewR943.plainReport(r);assert(txt.includes('10 MB'));assert(!txt.includes('yaklaşık'));assert.equal(h.c.SukunHealthViewR943.aiPayload(r).language,'en');assert(txt.includes('Not tried'));assert(!txt.includes('Denenmedi'));});
 await test('AI-payload-omits-all-raw-private-strings',()=>{const h=harness(),r=basic();r.timeline=[{secret:'PRIVATE_TIMELINE'}];r.current.prayer='PRIVATE_PRAYER';r.incidents=[{text:'PRIVATE_INCIDENT'}];r.checks.push({code:'HEAP',status:'WARN',evidence:{heapBytes:123,heapLimit:456,url:'PRIVATE_PATH',recording:'PRIVATE_AUDIO',key:'PRIVATE_KEY'}});const json=JSON.stringify(h.c.SukunHealthViewR943.aiPayload(r));for(const str of ['PRIVATE_TIMELINE','PRIVATE_PRAYER','PRIVATE_INCIDENT','PRIVATE_PATH','PRIVATE_AUDIO','PRIVATE_KEY'])assert(!json.includes(str));});
 await test('quick-collector-is-passive-and-does-not-fetch-or-SW-STATUS',async()=>{const h=harness(true),before=h.c.SukunHealthR940.read().current.session;const r=await h.c.SukunHealthR940.run({deep:false,online:true});assert.equal(h.fetches.length,0);assert.equal(h.transportCalls.length,0);assert.deepEqual(clone(r.current.session),clone(before));assert.equal(r.lastRun.online,false);assert.equal(r.checks.find(x=>x.code==='RUNTIME_INTEGRITY').status,'NOT_MEASURED');});
 await test('guided-reports-merge-fields-preserve-stamps-and-stay-user-reported',()=>{const h=harness(true),api=h.c.SukunHealthR940;api.recordDeviceCheck({manualCount:'AS_EXPECTED'});const first=api.read();api.recordDeviceCheck({lockedSound:'ISSUE',privateText:'PRIVATE'});const r=api.read();assert.equal(r.deviceCheck.source,'USER_REPORTED');assert.equal(r.deviceCheck.responses.manualCount,'AS_EXPECTED');assert.equal(r.deviceCheck.responses.lockedSound,'ISSUE');assert.equal(r.deviceCheck.observations.manualCount.at,first.deviceCheck.observations.manualCount.at);assert.equal(r.checks.find(x=>x.code==='DEVICE_AUDIO').status,'NOT_MEASURED');assert(!JSON.stringify(r).includes('PRIVATE'));assert.equal(h.transportCalls.length,0);});
 await test('issue-category-retains-original-marker-time-and-sequence',()=>{const h=harness(true),api=h.c.SukunHealthR940;const a=api.mark(),marker=a.timeline.find(x=>x.kind==='user-problem-marker');api.mark('audio');const rows=api.read().timeline.filter(x=>x.kind==='user-problem-marker');assert.equal(rows.length,1);assert.equal(rows[0].seq,marker.seq);assert.equal(rows[0].at,marker.at);assert.equal(rows[0].evidence.issueType,'audio');assert.equal(h.transportCalls.length,0);});
 await test('fresh-guided-trial-cannot-retimestamp-inherited-worked-answer',async()=>{const h=harness(),r=basic();r.deviceCheck={source:'USER_REPORTED',responses:{manualCount:'AS_EXPECTED',lockedSound:'ISSUE'},observations:{manualCount:{answer:'AS_EXPECTED',at:1,sessionEpoch:4},lockedSound:{answer:'ISSUE',at:2,sessionEpoch:4}}};let saved;h.c.SukunHealthViewR943.mount(h.panel,{read:()=>r,recordDeviceCheck:values=>{saved=values;return r;}});await h.click('tests');await h.click('guide-manual');await h.click('guide-next');await h.click('guide-next');const html=h.panel.querySelector('[data-health-content]').innerHTML;assert(html.includes('value="NOT_TRIED" selected'));assert(!html.includes('value="AS_EXPECTED" selected'));await h.click('device-save');assert.equal(saved.manualCount,'NOT_TRIED');assert(!('lockedSound'in saved));});
 await test('plain-report-includes-bounded-friendly-user-marker',()=>{const h=harness();h.c.I18N.lang='en';const r=basic();r.timeline=[{kind:'user-problem-marker',at:123,evidence:{issueType:'audio',private:'DO_NOT_EXPORT'}},{kind:'unrelated',at:123,evidence:{secret:'DO_NOT_EXPORT'}}];const txt=h.c.SukunHealthViewR943.plainReport(r);assert(txt.includes('Issues I marked'));assert(txt.includes('Audio'));assert(!txt.includes('DO_NOT_EXPORT'));});
 await test('isolated-model-result-does-not-alter-session-or-automatic-checks',async()=>{const h=harness(true),api=h.c.SukunHealthR940,before=api.read();h.c.SukunRegressionSoakLab={snapshot:()=>({active:false}),runMatrix:async()=>({type:'matrix',at:Date.now(),total:48,pass:48,fail:0,durationMs:22})};const r=await api.runModel();assert.equal(r.modelCheck.source,'ISOLATED_MODEL');assert.equal(r.modelCheck.total,48);assert.deepEqual(clone(r.current.session),clone(before.current.session));assert.deepEqual(clone(r.checks),clone(before.checks));assert.equal(h.transportCalls.length,0);});
 await test('integrity-incomplete-is-unknown-verified-corruption-and-config-fail',()=>{const h=harness(true),fn=h.c.SukunHealthR940.integrityResult;assert.equal(fn([{status:'HTTP_404'},{status:'SIZE_LIMIT'}],2,0).status,'NOT_MEASURED');assert.equal(fn([{status:'MATCH'}],2,100).status,'NOT_MEASURED');assert.equal(fn([],0,0).status,'NOT_MEASURED');assert.equal(fn([{status:'MATCH'}],1,100).status,'PASS');assert.equal(fn([{status:'HASH_MISMATCH'},{status:'HTTP_404'}],2,100).status,'FAIL');assert.equal(fn([{status:'INVALID_ENTRY'}],1,0).status,'FAIL');});
 function setupAI(){const h=harness(),r=basic();let current=r,calls=[];h.c.SukunAIRouter={hasAnyKey:()=>true,complete:args=>{calls.push(args);return new Promise((resolve,reject)=>h.pending={resolve,reject,args});}};const api={read:()=>current,run:async()=>current,mark:()=>current,close(){},recordDeviceCheck:()=>current};h.c.SukunHealthViewR943.mount(h.panel,api);return Object.assign(h,{r,calls,setReport:r=>current=r});}
 await test('AI-requires-preview-and-explicit-consent',async()=>{const h=setupAI();await h.click('explain');await h.click('ai-preview');await h.click('ai-send');assert.equal(h.calls.length,0);assert(h.panel.querySelector('[data-health-content]').innerHTML.includes('Gönderilecek içeriğin tamamı'));await h.consent();const p=h.click('ai-send');await Promise.resolve();assert.equal(h.calls.length,1);const payload=JSON.parse(h.calls[0].user);assert.equal(payload.schema,'sukun-health-ai-summary-r975');h.pending.resolve({text:'Only observed evidence.',providerLabel:'Test',model:'test'});await p;assert(h.panel.querySelector('[data-health-content]').innerHTML.includes('Only observed evidence.'));});
 await test('AI-own-connection-result-does-not-invalidate-matching-result',async()=>{const h=setupAI();await h.click('explain');await h.click('ai-preview');await h.consent();const p=h.click('ai-send');await Promise.resolve();const next=clone(h.r);next.checks.push({code:'AI_CONNECTIONS',status:'OBSERVED',evidence:{lastResult:{code:'OK'},providers:[{configured:true}]}});h.setReport(next);h.pending.resolve({text:'Own AI result accepted.'});await p;assert(h.panel.querySelector('[data-health-content]').innerHTML.includes('Own AI result accepted.'));});
 await test('AI-changed-report-is-rejected-before-network-send',async()=>{const h=setupAI();await h.click('explain');await h.click('ai-preview');await h.consent();const next=clone(h.r);next.lastRun.at=200;h.setReport(next);await h.click('ai-send');assert.equal(h.calls.length,0);});
 await test('AI-stale-inflight-answer-is-discarded',async()=>{const h=setupAI();await h.click('explain');await h.click('ai-preview');await h.consent();const p=h.click('ai-send');await Promise.resolve();const next=clone(h.r);next.current.session.epoch=9;h.setReport(next);h.pending.resolve({text:'STALE ANSWER'});await p;assert(!h.panel.querySelector('[data-health-content]').innerHTML.includes('STALE ANSWER'));});
 await test('AI-cancel-aborts-request-and-releases-busy-state',async()=>{const h=setupAI();await h.click('explain');await h.click('ai-preview');await h.consent();const p=h.click('ai-send');await Promise.resolve();await h.click('cancel');await p;assert(h.calls[0].signal.aborted);assert.equal(h.panel.getAttribute('aria-busy'),'false');h.pending.resolve({text:'LATE'});await Promise.resolve();assert(!h.panel.querySelector('[data-health-content]').innerHTML.includes('LATE'));});
 await test('AI-deadline-aborts-even-if-router-never-settles',async()=>{const h=setupAI();await h.click('explain');await h.click('ai-preview');await h.consent();const p=h.click('ai-send');await Promise.resolve();const timer=[...h.timers.values()].find(x=>x.ms===42000);assert(timer);timer.fn();await p;assert(h.calls[0].signal.aborted);assert.equal(h.panel.getAttribute('aria-busy'),'false');});
 await test('offline-local-explanation-works-and-AI-is-not-sent',async()=>{const h=setupAI();h.c.navigator.onLine=false;await h.click('explain');assert(h.panel.querySelector('[data-health-content]').innerHTML.includes('YEREL AÇIKLAMA'));assert(!h.panel.querySelector('[data-health-action="ai-preview"]'));assert.equal(h.calls.length,0);});
 await test('language-change-refreshes-guides-and-cancels-existing-AI-consent',async()=>{const h=setupAI();await h.click('tests');await h.click('guide-manual');h.c.I18N.lang='en';await h.c.dispatch('sukun:languagechange');assert(h.panel.querySelector('[data-health-content]').innerHTML.includes('Pause'));assert.equal(JSON.parse(JSON.stringify(h.c.SukunHealthViewR943.aiPayload(h.r))).language,'en');});
 await test('safe-render-escapes-AI-HTML',async()=>{const h=setupAI();await h.click('explain');await h.click('ai-preview');await h.consent();const p=h.click('ai-send');await Promise.resolve();h.pending.resolve({text:'<img src=x onerror=alert(1)>'});await p;const html=h.panel.querySelector('[data-health-content]').innerHTML;assert(html.includes('&lt;img'));assert(!html.includes('<img src=x'));});
 function integrityHost(entries,bodies,options={}) {
  const start=collector.indexOf('  async function responseBytes('),end=collector.indexOf('  function sampleExplicit()',start);assert(start>0&&end>start);
  let abortTimer,active=0,maxActive=0;const calls=[];
  const c={URL,Response,AbortController,DOMException,TextDecoder,Uint8Array,crypto:crypto.webcrypto,build:'r986',now:()=>Date.now(),location:{href:'https://test.invalid/sukun/nero.html',origin:'https://test.invalid'},navigator:{onLine:true},path:u=>new URL(u).pathname,token:String,status:(code,status,title,evidence)=>({code,status,evidence}),setTimeout:(fn,ms)=>{if(ms===10000)abortTimer=fn;return 1;},clearTimeout(){}};
  c.fetch=async(url,args)=>{calls.push(url);const p=new URL(url).pathname.replace('/sukun/','');if(p==='sukun-build-r986.json')return new Response(JSON.stringify({build:'r986',runtime:entries}));active++;maxActive=Math.max(active,maxActive);
   try {if(options.block===p){queueMicrotask(()=>abortTimer());await new Promise((resolve,reject)=>{args.signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true});if(args.signal.aborted)reject(new DOMException('Aborted','AbortError'));});}await new Promise(resolve=>setImmediate(resolve));return new Response(bodies.get(p),{headers:{'content-length':bodies.get(p).length}});}finally{active--;}};
  vm.createContext(c);vm.runInContext(collector.slice(start,end),c);return {c,calls,getMaxActive:()=>maxActive};
 }
 function fixture(sizeList) {const names=['gold','copper','silver','dark','crystal'],bodies=new Map(),entries=sizeList.map((size,index)=>{const p='assets/wheel-navigation-r964/'+names[index]+'.png',bytes=Buffer.alloc(size,index+1);bodies.set(p,bytes);return {url:'./'+p,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};});return {entries,bodies};}
 function runtimeCountFixture(count) {const bodies=new Map(),entries=Array.from({length:count},(_,index)=>{const p='assets/runtime/count-bound-'+index+'.js',bytes=Buffer.from('/* fixture '+index+' */');bodies.set(p,bytes);return {url:'./'+p,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};});return {entries,bodies};}
 await test('current-manifest-files-verify-under-8MiB-with-two-workers',async()=>{const markerFile=fs.readdirSync(root).filter(x=>/^sukun-build-r\d+\.json$/.test(x)).sort((a,b)=>Number(a.match(/r(\d+)/)[1])-Number(b.match(/r(\d+)/)[1])).at(-1);const marker=JSON.parse(fs.readFileSync(root+'/'+markerFile,'utf8')),bodies=new Map(),entries=marker.runtime.map(entry=>{const p=new URL(entry.url,'https://test.invalid/').pathname.slice(1),bytes=fs.readFileSync(root+'/'+p);bodies.set(p,bytes);return {...entry,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};});assert.equal(entries.length,new Set(entries.map(x=>x.url)).size);const host=integrityHost(entries,bodies),r=await host.c.integrityCheck();assert.equal(r.status,'PASS');assert.equal(r.evidence.files.length,marker.runtime.length);assert(r.evidence.files.every(x=>x.status==='MATCH'));assert(r.evidence.bytes>0&&r.evidence.bytes<8388608);assert(host.getMaxActive()<=2);});
 await test('bounded-manifest-count-allows64-valid-entries-with-two-workers',async()=>{const f=runtimeCountFixture(64),host=integrityHost(f.entries,f.bodies),r=await host.c.integrityCheck();assert.equal(r.status,'PASS');assert.equal(r.evidence.expected,64);assert.equal(r.evidence.files.length,64);assert(r.evidence.files.every(x=>x.status==='MATCH'));assert(host.getMaxActive()<=2);});
 await test('bounded-manifest-count-rejects65-before-any-asset-download',async()=>{const f=runtimeCountFixture(65),host=integrityHost(f.entries,f.bodies),r=await host.c.integrityCheck();assert.equal(r.status,'FAIL');assert.equal(r.evidence.reason,'MARKER_INVALID');assert.equal(r.evidence.configurationErrors,1);assert.equal(host.calls.length,1);assert.equal(host.getMaxActive(),0);});
 await test('remaining-budget-downloads-smaller-last-file-without-false-limit',async()=>{const f=fixture([1800000,1800000,1800000,1800000,1000000]),host=integrityHost(f.entries,f.bodies),r=await host.c.integrityCheck();assert.equal(r.status,'PASS');assert.equal(r.evidence.bytes,8200000);assert(r.evidence.files.every(x=>x.status==='MATCH'));assert(host.getMaxActive()<=2);});
 await test('actual-over-budget-is-incomplete-and-bounded-not-corrupt',async()=>{const f=fixture([2097152,2097152,2097152,2097152,2097152]),host=integrityHost(f.entries,f.bodies),r=await host.c.integrityCheck();assert.equal(r.status,'NOT_MEASURED');assert.equal(r.evidence.bytes,8388608);assert.equal(r.evidence.files.filter(x=>x.status==='MATCH').length,4);assert.equal(r.evidence.files.filter(x=>x.status==='TOTAL_SIZE_LIMIT').length,1);assert(host.getMaxActive()<=2);});
 await test('abort-wakes-reservation-waiter-without-deadlock',async()=>{const f=fixture([2097152,2097152,2097152,2097152,2097152]),host=integrityHost(f.entries,f.bodies,{block:'assets/wheel-navigation-r964/dark.png'});let watchdog;const r=await Promise.race([host.c.integrityCheck(),new Promise((_,reject)=>watchdog=setTimeout(()=>reject(Error('reservation deadlock')),1000))]).finally(()=>clearTimeout(watchdog));assert.equal(r.status,'NOT_MEASURED');assert.equal(r.evidence.files.length,5);assert(r.evidence.files.some(x=>x.status==='TIMEOUT'));assert(host.getMaxActive()<=2);});
 fs.mkdirSync(__dirname+'/evidence',{recursive:true});fs.writeFileSync(__dirname+'/evidence/health_ui_results.json',JSON.stringify({fixtureBuild:'r986',source:root,collectorSha256:require('crypto').createHash('sha256').update(collector).digest('hex'),presenterSha256:require('crypto').createHash('sha256').update(view).digest('hex'),method:'Production collector/presenter functions in deterministic modeled DOM and timer/AI stubs. No browser, physical sound, screen-lock, or Android crash guarantee.',passed:results.length,results},null,2));console.log(JSON.stringify({passed:results.length,results},null,2));
})().catch(e=>{console.error(e.stack||e);console.error('passed before failure:',results.map(x=>x.id));process.exitCode=1;});
