#!/usr/bin/env node
'use strict';
// Executes the entire shipped r187 UI/runtime against controlled DOM and timers.
// No browser, network, real IndexedDB, user recording or recording contents are used.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..'));
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const match=html.match(/<script id="sukun-r187-record-safety-runtime">([\s\S]*?)<\/script>/);
assert(match,'Shipped recording-safety script exists');
const source=match[1],results=[];
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
const successful=(count=2,blobBytes=8192,at=1791219600000)=>({at,build:'r1017',status:'ok',count,blobBytes,errorCode:null});
const failed=(status='unavailable',errorCode='read-failed',at=1791219602000)=>({at,build:'r1017',status,count:null,blobBytes:null,errorCode});
const tick=async()=>{for(let i=0;i<24;i++)await Promise.resolve();};
function fixture(options={}){
  const nodes=new Map(),events=new Map(),timers=new Map(),calls=[],inspectionCalls=[];
  let timerId=0,snapshotCalls=0,handler=options.handler||(()=>Promise.resolve(successful()));
  let cached={version:'r1017',phase:'idle',current:null,lastSuccessful:null,persistence:'available',...options.cached};
  class Node{
    constructor(tag='div',id=null){this.tagName=tag.toUpperCase();this.id=id;this.attributes={};this.disabled=false;this.hidden=false;this.textContent='';this._html='';this.children=[];this.onclick=null;if(id)nodes.set(id,this);}
    setAttribute(name,value){this.attributes[name]=String(value);if(name==='disabled')this.disabled=true;}
    getAttribute(name){return this.attributes[name]??null;}
    set innerHTML(value){this._html=value;for(const tag of value.matchAll(/<(\w+)\b([^>]*)>/g)){const attrs=tag[2],id=/\bid="([^"]+)"/.exec(attrs)?.[1];if(!id)continue;const node=new Node(tag[1],id);for(const a of attrs.matchAll(/([\w-]+)="([^"]*)"/g))node.setAttribute(a[1],a[2]);node.disabled=/\sdisabled(?:\s|$)/.test(attrs);node.hidden=/\shidden(?:\s|$)/.test(attrs);this.children.push(node);}}
    get innerHTML(){return this._html;}
    querySelector(selector){if(selector==='summary')return this.summary||null;if(selector.startsWith('#'))return nodes.get(selector.slice(1))||null;return null;}
    prepend(node){this.children.unshift(node);node.parentNode=this;}
    insertAdjacentElement(_where,node){this.parentNode?.children.push(node);}
    click(){if(this.disabled)return;return this.onclick?.();}
  }
  const host=new Node('details','ydkBox');
  const api={version:'r1017',snapshot(){snapshotCalls++;if(options.snapshotThrows)throw new Error('SECRET_KEY');return cached;},inspect(args){inspectionCalls.push(args);cached.phase='reading';return handler(args);}};
  const touched=name=>(...args)=>{calls.push(name);return args;};
  const c={Promise,Number,String,Date,Math,Object,Array,Error,AbortController:options.noAbort?undefined:AbortController,
    location:{protocol:options.web?'https:':'file:',origin:options.web?'https://example.test':'null',host:options.web?'example.test':''},
    document:{readyState:'complete',getElementById:id=>nodes.get(id)||null,querySelector:s=>s==='meta[name="sukun-build"]'?{getAttribute:()=>options.build||'r1017'}:s.startsWith('#')?nodes.get(s.slice(1))||null:null,createElement:tag=>new Node(tag),addEventListener(type,fn){events.set('document:'+type,fn);}},
    addEventListener(type,fn){events.set(type,fn);},setTimeout(fn,ms){const id=++timerId;timers.set(id,{fn,ms});return id;},clearTimeout(id){timers.delete(id);},
    skRecordingCatalogRead:async()=>{calls.push('catalog.read');return {ok:true,keys:options.autoKeys||['existing']};},
    skRecordingCatalogWarning:()=> 'Depo okunamadı; kayıtların silindiği anlamına gelmez.',hesc:String,
    itemRecSyncUI:touched('itemRecSyncUI'),recCountUI:touched('recCountUI'),recMgrRender:touched('recMgrRender'),ydkListe:touched('ydkListe'),svkInit:touched('svkInit'),tvkInit:touched('tvkInit'),veriDurumYaz:touched('veriDurumYaz'),
    recInit:touched('recInit'),toast:touched('toast'),showToast:touched('showToast'),Audio:touched('Audio'),fetch:touched('fetch'),
    indexedDB:new Proxy({},{get(_target,name){calls.push('indexedDB.'+String(name));throw Error('Unexpected storage access');}}),
    REC_DB:new Proxy({},{get(_target,name){calls.push('REC_DB.'+String(name));throw Error('Unexpected recording access');}}),
  };
  c.window=c;if(!options.noAPI)c.SukunRecordingInspection=api;
  vm.createContext(c);vm.runInContext(source,c,{filename:'shipped-r187-ui.js'});
  return {c,nodes,events,timers,calls,inspectionCalls,api,host,
    get button(){return nodes.get('r1017RecInspect');},get cancel(){return nodes.get('r1017RecInspectionCancel');},get oldButton(){return nodes.get('r187RecRescan');},
    get status(){return nodes.get('r1017RecInspectionStatus');},get history(){return nodes.get('r1017RecInspectionHistory');},get persistence(){return nodes.get('r1017RecInspectionPersistence');},
    snapshots:()=>snapshotCalls,setHandler(fn){handler=fn;},setCached(value){cached={...cached,...value};},
    async timer(ms){const entry=[...timers].find(([,job])=>job.ms===ms);assert(entry,'timer '+ms);timers.delete(entry[0]);entry[1].fn();await tick();},
  };
}
function untouched(h){assert.deepEqual(h.calls,[],'No catalog, recording, UI initializer, audio or network function ran');}
async function test(name,fn){try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.stack});}}
(async()=>{
  await test('installed old manual button is visibly/native/ARIA disabled and actual onclick is harmless',async()=>{
    const h=fixture();assert.equal(h.oldButton.disabled,true);assert.equal(h.oldButton.getAttribute('aria-disabled'),'true');assert.match(h.host.children[0].innerHTML,/Kayıtları yeniden tara \(geçici olarak durduruldu\)/);assert.equal(h.oldButton.click(),undefined);assert.equal(await h.oldButton.onclick(),false);untouched(h);assert.equal(h.inspectionCalls.length,0);
  });
  await test('public manual true route is a function-level no-op before storage or any UI work',async()=>{
    const h=fixture(),before=h.nodes.get('r187RecStat').innerHTML;assert.equal(await h.c.SUKUN_REC_RESCAN(true),null);assert.equal(h.nodes.get('r187RecStat').innerHTML,before);untouched(h);assert.equal(h.inspectionCalls.length,0);
  });
  await test('truthy programmatic manual variants cannot bypass paused route',async()=>{const h=fixture();for(const flag of [1,'true',{},[]])assert.equal(await h.c.SUKUN_REC_RESCAN(flag),null);untouched(h);});
  await test('automatic false route still invokes original catalog and UI initializers',async()=>{const h=fixture();assert.deepEqual([...await h.c.SUKUN_REC_RESCAN(false)],['existing']);assert.deepEqual(h.calls,['catalog.read','itemRecSyncUI','recCountUI','recMgrRender','ydkListe','svkInit','tvkInit','veriDurumYaz']);});
  await test('automatic delayed recovery still waits 350 ms and uses original false route',async()=>{const h=fixture({web:true});untouched(h);assert.equal(h.timers.size,1);await h.timer(350);assert.equal(h.calls.filter(x=>x==='catalog.read').length,1);assert.equal(h.inspectionCalls.length,0);});
  await test('empty automatic recovery retains its original delayed retry',async()=>{const h=fixture({web:true,autoKeys:[]});await h.timer(350);await tick();await h.timer(900);assert.equal(h.calls.filter(x=>x==='catalog.read').length,2);assert.equal(h.inspectionCalls.length,0);});
  await test('post-import call remains explicitly false in production source',async()=>{assert.match(html,/await window\.SUKUN_REC_RESCAN\?\.\(false\)/);});
  await test('opening UI renders one cached snapshot and does not inspect',async()=>{const h=fixture();assert.equal(h.snapshots(),1);assert.equal(h.inspectionCalls.length,0);assert.match(h.status.textContent,/Henüz bir kontrol yapılmadı/);assert.equal(h.cancel.hidden,true);assert.equal(h.button.disabled,false);untouched(h);});
  await test('new panel explains paused action and read-only observation without recovery promise',async()=>{const h=fixture();const markup=h.host.children[0].innerHTML;assert.match(markup,/Kayıt sorunu incelenirken elle yeniden tarama geçici olarak durduruldu/);assert.match(markup,/yalnızca kayıt deposunu okur; kayıtları değiştirmez ve kayıt kurtarma işlemi değildir/);assert.match(markup,/Kayıt deposunu kontrol et/);assert.equal(h.status.getAttribute('role'),'status');assert.equal(h.status.getAttribute('aria-live'),'polite');});
  await test('explicit check gets current count, aggregate bytes, timestamp and build only from observer',async()=>{const h=fixture();await h.button.onclick();assert.equal(h.inspectionCalls.length,1);assert(h.inspectionCalls[0].signal instanceof AbortSignal);assert.match(h.status.textContent,/Son kontrol:/);assert.match(h.status.textContent,/Derleme: r1017/);assert.match(h.status.textContent,/Bu kontrol: 2 kayıt · toplam 8\.192 bayt/);assert.equal(h.history.hidden,true);assert.equal(h.button.disabled,false);assert.equal(h.cancel.hidden,true);untouched(h);});
  await test('confirmed empty observation shows genuine zero count and bytes',async()=>{const h=fixture({handler:()=>Promise.resolve(successful(0,0))});await h.button.onclick();assert.match(h.status.textContent,/Bu kontrol: 0 kayıt · toplam 0 bayt/);untouched(h);});
  await test('reading disables repeated direct and native clicks and exposes cancel',async()=>{const wait=deferred(),h=fixture({handler:()=>wait.promise});const pending=h.button.onclick();assert.equal(h.button.disabled,true);assert.equal(h.button.getAttribute('aria-disabled'),'true');assert.equal(h.cancel.hidden,false);assert.equal(h.status.getAttribute('aria-busy'),'true');h.button.click();await h.button.onclick();assert.equal(h.inspectionCalls.length,1);assert.match(h.status.textContent,/Kontrol sürüyor/);wait.resolve(successful());await pending;untouched(h);});
  await test('cancel aborts signal immediately, restores controls and shows no zero count',async()=>{const wait=deferred(),h=fixture({handler:()=>wait.promise});const pending=h.button.onclick();h.cancel.onclick();assert.equal(h.inspectionCalls[0].signal.aborted,true);assert.equal(h.button.disabled,false);assert.equal(h.cancel.hidden,true);assert.match(h.status.textContent,/iptal edildi/);assert.doesNotMatch(h.status.textContent,/0 kayıt|Bu kontrol:/);wait.resolve(successful());await pending;assert.match(h.status.textContent,/iptal edildi/);untouched(h);});
  await test('cancelled late rejection cannot repaint cancelled state',async()=>{const wait=deferred(),h=fixture({handler:()=>wait.promise});const pending=h.button.onclick();h.cancel.onclick();const before=h.status.textContent;wait.reject(new Error('PRIVATE RECORDING KEY'));await pending;assert.equal(h.status.textContent,before);untouched(h);});
  await test('repeat after cancellation starts a new operation and old success cannot replace it',async()=>{const first=deferred(),second=deferred(),h=fixture({handler:()=>first.promise});const p1=h.button.onclick();h.cancel.onclick();h.setHandler(()=>second.promise);const p2=h.button.onclick();first.resolve(successful(100,999999));await p1;assert.equal(h.button.disabled,true);assert.match(h.status.textContent,/Kontrol sürüyor/);second.resolve(successful(3,12));await p2;assert.match(h.status.textContent,/Bu kontrol: 3 kayıt · toplam 12 bayt/);assert.equal(h.inspectionCalls.length,2);untouched(h);});
  await test('late cancelled result cannot replace newer completed success',async()=>{const first=deferred(),h=fixture({handler:()=>first.promise});const p1=h.button.onclick();h.cancel.onclick();h.setHandler(()=>Promise.resolve(successful(4,16)));await h.button.onclick();const before=h.status.textContent;first.resolve(successful(99,999));await p1;assert.equal(h.status.textContent,before);untouched(h);});
  await test('pagehide cancels owned inspection and fences delayed success',async()=>{const wait=deferred(),h=fixture({handler:()=>wait.promise});const pending=h.button.onclick();h.events.get('pagehide')();const before=h.status.textContent;assert.equal(h.inspectionCalls[0].signal.aborted,true);h.events.get('pagehide')();wait.resolve(successful());await pending;assert.equal(h.status.textContent,before);assert.match(before,/iptal edildi/);untouched(h);});
  await test('cancelled observation uses actual page build rather than fixed observer version',async()=>{const wait=deferred(),h=fixture({build:'r1111',handler:()=>wait.promise});const pending=h.button.onclick();assert.match(h.status.textContent,/Derleme: r1111/);h.cancel.onclick();assert.match(h.status.textContent,/Derleme: r1111/);wait.resolve(successful());await pending;assert.match(h.status.textContent,/Derleme: r1111/);untouched(h);});
  await test('idle pagehide does not create an observation or change controls',async()=>{const h=fixture();const before=h.status.textContent;h.events.get('pagehide')();assert.equal(h.status.textContent,before);assert.equal(h.inspectionCalls.length,0);untouched(h);});
  await test('prior successful result is historical during reading and after failed new check',async()=>{const previous=successful(7,49),wait=deferred(),h=fixture({cached:{current:previous,lastSuccessful:previous},handler:()=>wait.promise});assert.equal(h.history.hidden,true);const pending=h.button.onclick();assert.equal(h.history.hidden,false);assert.match(h.history.textContent,/Önceki başarılı kontrol \(geçmiş bilgi\)/);assert.match(h.history.textContent,/7 kayıt/);assert.doesNotMatch(h.status.textContent,/7 kayıt/);wait.resolve(failed());await pending;assert.match(h.status.textContent,/şu anda okunamıyor/);assert.doesNotMatch(h.status.textContent,/7 kayıt|0 kayıt/);assert.match(h.history.textContent,/güncel bir kontrol sonucu değildir/);untouched(h);});
  await test('persisted failed current remains failed beside separately labeled historical success',async()=>{const h=fixture({cached:{current:failed(),lastSuccessful:successful(8,64)}});assert.match(h.status.textContent,/şu anda okunamıyor/);assert.doesNotMatch(h.status.textContent,/8 kayıt|0 kayıt/);assert.match(h.history.textContent,/8 kayıt/);assert.equal(h.inspectionCalls.length,0);untouched(h);});
  for(const [state,code,word] of [['missing','db-missing','bulunamadı'],['missing','store-missing','kayıt bölümü'],['unsupported','idb-unavailable','desteklenmiyor'],['unavailable','read-failed','okunamıyor'],['timed-out','read-timeout','zaman aşımına'],['cancelled','inspection-cancelled','iptal edildi'],['blocked','db-blocked','engellendi']]){
    await test('non-success '+state+'/'+code+' has explicit fixed explanation and never fabricated zero',async()=>{const h=fixture({handler:()=>Promise.resolve({...failed(state,code),count:0,blobBytes:0})});await h.button.onclick();assert.match(h.status.textContent,new RegExp(word));assert.match(h.status.textContent,/sayı[sı]* ve toplam boyut belirlenemedi|kayıt sayısı ve toplam boyut belirlenemedi/);assert.doesNotMatch(h.status.textContent,/0 kayıt|toplam 0 bayt|Bu kontrol:/);untouched(h);});
  }
  await test('arbitrary returned status, error strings and malformed build never appear in UI',async()=>{const h=fixture({handler:()=>Promise.resolve({...failed('PRIVATE_STATUS','PRIVATE_RECORD_KEY'),build:'<audio src="private-name">'})});await h.button.onclick();assert.doesNotMatch(h.status.textContent,/PRIVATE|private-name|audio/);assert.match(h.status.textContent,/Derleme: bilinmiyor/);untouched(h);});
  await test('prototype property names are not accepted as localized status/error labels',async()=>{const h=fixture({handler:()=>Promise.resolve(failed('__proto__','constructor'))});await h.button.onclick();assert.match(h.status.textContent,/şu anda okunamıyor/);assert.doesNotMatch(h.status.textContent,/\[object|function Object/);untouched(h);});
  await test('rejected observer error is sanitized without message or key disclosure',async()=>{const h=fixture({handler:()=>Promise.reject(new Error('PRIVATE_RECORDING_NAME'))});await h.button.onclick();assert.match(h.status.textContent,/Kontrol tamamlanamadı/);assert.doesNotMatch(h.status.textContent,/PRIVATE_RECORDING_NAME/);assert.equal(h.button.disabled,false);untouched(h);});
  await test('invalid successful aggregate is treated as unavailable instead of current evidence',async()=>{for(const malformed of [{count:-1},{blobBytes:Infinity},{count:0.5},{blobBytes:null},{errorCode:'read-failed'}]){const h=fixture({handler:()=>Promise.resolve({...successful(),...malformed})});await h.button.onclick();assert.match(h.status.textContent,/belirlenemedi/);assert.doesNotMatch(h.status.textContent,/Bu kontrol:/);assert.equal(h.history.hidden,true);untouched(h);}});
  await test('missing observer component fails visibly only on explicit check',async()=>{const h=fixture({noAPI:true});assert.match(h.status.textContent,/Henüz/);await h.button.onclick();assert.match(h.status.textContent,/Kontrol bileşeni kullanılamıyor/);assert.equal(h.inspectionCalls.length,0);untouched(h);});
  await test('without AbortController UI does not begin uncancellable observer work',async()=>{const h=fixture({noAbort:true});await h.button.onclick();assert.match(h.status.textContent,/güvenli iptali desteklemiyor/);assert.equal(h.inspectionCalls.length,0);untouched(h);});
  await test('snapshot exception does not trigger probe or leak error string',async()=>{const h=fixture({snapshotThrows:true});assert.equal(h.inspectionCalls.length,0);await h.button.onclick();assert.match(h.status.textContent,/Bu kontrol: 2 kayıt/);assert.doesNotMatch(h.status.textContent,/SECRET_KEY/);untouched(h);});
  await test('unavailable history persistence is labeled separately from current store result',async()=>{const h=fixture({cached:{persistence:'unavailable'}});assert.equal(h.persistence.hidden,false);assert.match(h.persistence.textContent,/Kontrol geçmişi bu tarayıcıda saklanamıyor/);await h.button.onclick();assert.match(h.status.textContent,/Bu kontrol: 2 kayıt/);assert.match(h.persistence.textContent,/kayıt deposunun boş olduğu anlamına gelmez/);untouched(h);});
  await test('repeated successful clicks perform distinct observations and re-enable the control',async()=>{const h=fixture();await h.button.onclick();h.setHandler(()=>Promise.resolve(successful(5,20)));await h.button.onclick();assert.equal(h.inspectionCalls.length,2);assert.match(h.status.textContent,/Bu kontrol: 5 kayıt · toplam 20 bayt/);assert.equal(h.button.disabled,false);untouched(h);});
  await test('new UI code contains no direct recording store, destructive, media or network route',async()=>{const ui=source.slice(source.indexOf('function bindRecordingInspectionUI(){'),source.indexOf('function syncSafetyUI('));for(const forbidden of [/REC_DB/,/skRecordingCatalog/,/rescanRecordings/,/indexedDB/,/\.delete\(/,/\.clear\(/,/\.put\(/,/fetch\(/,/new Audio/,/recMgrRender/,/svkInit/,/tvkInit/,/itemRecSyncUI/])assert.doesNotMatch(ui,forbidden);});
  await test('new inspection controls have scoped 44px touch targets and readable 12px text',async()=>{const rule=html.match(/\.recInspectionActions \.recRescueBtn\{([^}]*)\}/)?.[1];assert(rule);assert.match(rule,/min-height:44px!important/);assert.match(rule,/font-size:12px!important/);assert.match(rule,/white-space:normal/);assert.match(rule,/min-width:0/);assert.match(html,/\.recRescueBtn\{min-height:32px!important;padding:6px 9px!important;font-size:9px!important;white-space:nowrap\}/);});
  await test('entry HTML copies remain byte-identical',async()=>{assert.equal(html,fs.readFileSync(path.join(root,'nero.html'),'utf8'));});
  const report={root,sourceSha256:crypto.createHash('sha256').update(html).digest('hex'),method:'Entire shipped r187 runtime executed with controlled DOM, observation API and timers; native-disabled semantics are modeled. No browser, real storage, recording content or physical-device deletion test.',passed:results.filter(r=>r.passed).length,total:results.length,results};
  fs.writeFileSync(path.join(__dirname,'ui_recording_inspection_results.json'),JSON.stringify(report,null,2)+'\n');
  console.log(JSON.stringify(report,null,2));process.exitCode=report.passed===report.total?0:1;
})().catch(error=>{console.error(error);process.exitCode=1});
