'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),zlib=require('zlib'),crypto=require('crypto');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..'));
const png=fs.readFileSync(path.join(root,'assets/branding/sukun-frameless-logo-r1029.png')),original=fs.readFileSync(path.join(root,'icon-512-maskable.png')),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const results=[];function test(name,fn){try{fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function decode(b){assert.equal(b.subarray(1,4).toString(),'PNG');let at=8,w,h,color,depth,interlace,idat=[];while(at<b.length){const n=b.readUInt32BE(at),type=b.subarray(at+4,at+8).toString(),d=b.subarray(at+8,at+8+n);at+=n+12;if(type==='IHDR'){w=d.readUInt32BE(0);h=d.readUInt32BE(4);depth=d[8];color=d[9];interlace=d[12];}if(type==='IDAT')idat.push(d);if(type==='IEND')break;}assert.equal(depth,8);assert.equal(interlace,0);assert([2,6].includes(color));const channels=color===6?4:3,stride=w*channels,raw=zlib.inflateSync(Buffer.concat(idat)),out=Buffer.alloc(stride*h);let p=0;const paeth=(a,b,c)=>{const q=a+b-c,pa=Math.abs(q-a),pb=Math.abs(q-b),pc=Math.abs(q-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};for(let y=0;y<h;y++){const filter=raw[p++];for(let x=0;x<stride;x++){const a=x>=channels?out[y*stride+x-channels]:0,b=y?out[(y-1)*stride+x]:0,c=y&&x>=channels?out[(y-1)*stride+x-channels]:0,v=raw[p++];assert(filter<=4);out[y*stride+x]=(v+(filter===0?0:filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):paeth(a,b,c)))&255;}}return {w,h,channels,pixels:out};}
const a=decode(png),s=decode(original),alpha=(x,y)=>a.pixels[(y*a.w+x)*4+3],style=html.match(/<style id="sukun-auto-intro-style">([\s\S]*?)<\/style>/)[1];
test('Original maskable source stays byte-identical',()=>assert.equal(hash(original),'c2fe296ba7fc962e5ab7c1a4164e96bf08b6ef21b1fb709c2059f1b66d98333d'));
test('Approved original-only alpha extraction is exact',()=>assert.equal(hash(png),'19686a971a82137067622b90a9984ac146e68c3e7e9b82395dfc19462f4ffdcd'));
test('No crop or resize: both canvases are 512 square',()=>{assert.deepEqual([a.w,a.h,s.w,s.h],[512,512,512,512]);assert.equal(a.channels,4);});
test('All four canvas edges are fully transparent',()=>{for(let k=0;k<512;k++)assert.equal(alpha(k,0)+alpha(k,511)+alpha(0,k)+alpha(511,k),0);});
test('Foreground opaque RGB is retained exactly',()=>{let n=0;for(let i=0;i<512*512;i++)if(a.pixels[i*4+3]===255){n++;for(let k=0;k<3;k++)assert.equal(a.pixels[i*4+k],s.pixels[i*s.channels+k]);}assert.equal(n,9985);});
test('Only documented matte edge pixels are partially transparent',()=>{let n=0;for(let i=3;i<a.pixels.length;i+=4)if(a.pixels[i]>0&&a.pixels[i]<255)n++;assert.equal(n,3079);});
test('Dark square background is actually removed, not CSS-opacity hidden',()=>{let n=0;for(let i=3;i<a.pixels.length;i+=4)if(a.pixels[i]===0)n++;assert.equal(n,249080);assert(!style.includes('mix-blend-mode'));assert(!/img\{[^}]*mask-image/.test(style));});
test('No stray alpha exists outside original foreground bounds',()=>{for(let y=0;y<512;y++)for(let x=0;x<512;x++)if(x<156||x>=357||y<91||y>=420)assert.equal(alpha(x,y),0);});
test('Original emblem and wordmark both remain visible',()=>{let upper=0,lower=0;for(let y=0;y<512;y++)for(let x=0;x<512;x++)if(alpha(x,y)){if(y<360)upper++;else lower++;}assert(upper>9000);assert(lower>1000);});
test('Only one logo image is rendered, with no extra heading or tap prompt',()=>{const body=html.match(/<div id="sukun-auto-intro"[^>]*>([\s\S]*?)<script id="sukun-auto-intro-clock">/)[1];assert.equal((body.match(/<img\b/g)||[]).length,1);assert(!/<button|<h[1-6]|dokun|tap|apMuhur/i.test(body));});
test('Background fills the viewport in green/gold, without logo duplication',()=>{assert.match(style,/#sukun-auto-intro\{position:fixed;inset:0/);assert.match(style,/#173b29/);assert.match(style,/sukun-intro-pattern-r1029\.svg/);assert(!/background[^;}]*frameless-logo/.test(style));});
test('Pattern is code-native scalable geometry without text or raster image',()=>{const svg=fs.readFileSync(path.join(root,'assets/branding/sukun-intro-pattern-r1029.svg'),'utf8');assert.match(svg,/<svg[^>]+viewBox="0 0 160 160"/);assert.match(svg,/<path/);assert(!/<text|<image|base64/.test(svg));});
test('Pulse has one approach and retreat, no infinite loop',()=>{const frames=style.match(/@keyframes sukunIntroMark\{(.*?)\}\n/s)[1];assert.match(frames,/scale\(1\.055\)/);assert.match(frames,/scale\(\.985\)/);assert(!style.includes('infinite'));});
test('No application or ancestor layout is animated by intro CSS',()=>{assert(!/(?:^|\})\s*(?:html|body|#tk|#r170Now)[\s,{:]/m.test(style));assert.match(style,/isolation:isolate/);assert.match(style,/pointer-events:none!important/);});
test('Independent4.8-second exit and reduced-motion fallback remain',()=>{assert.match(style,/animation:sukunIntroExit 4\.8s linear 1s both/);assert.match(style,/prefers-reduced-motion:reduce/);assert.match(html,/timing.duration!==4800/);});
test('Optional audio has one bounded automatic resume and no later input unlock',()=>{const js=fs.readFileSync(path.join(root,'assets/runtime/startup-intro-r1027.js'),'utf8');assert.match(js,/INTRO_MS=4800,HIT_MS=3000/);assert.equal((js.match(/context\.resume\(/g)||[]).length,1);assert.match(js,/function input\(event\)\{if\(event\.isTrusted===true\)stop\('cancelled'\);\}/);assert.match(js,/if\(stopped\|\|playing\|\|!resumeReady\|\|!buffer\|\|!context\|\|context\.state!=='running'\)return/);assert(!/\.(?:acquire|setItem|removeItem)\s*\(/.test(js));});
const report={total:results.length,passed:results.filter(x=>x.passed).length,results,scope:'PNG alpha/source-pixel and CSS/audio contract checks. Flattened source edge alpha is estimated; no physical autoplay or Android notification render claimed.'};console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;

